- stack-single.yml
- stack.yml
- templates/stack.yml.j2
Add dependency of FIP to router interface.
The manager floating ip needs to be associated with a fixed IP address
that is L3 reachable from the public network that we allocate the FIP
from. neutron rightly enforces it, the heat template correctly attaches
the subnet to the router but it misses the dependency, so we hit a race.
Adding a depency fixes it and makes the deployment succeed on CityCloud.
> Fix Floating IP race

- environments/secrets.yml
Necessary for the use of Cockpit. A login from outside
on the manager via SSH is not possible because the
password authentication is disabled.
> Set operator password

- README.md
- environment.yml
OK, this is a straight bugfix.
You misnamed the flavor_node as flavor_controller in environment.yml and the documentation.
Fixed with these patches.
> Testbed flavor name

- README.md
- environment.yml
- stack-single.yml
- stack.yml
- templates/stack.yml.j2
This allows to specify ceph_version and openstack_version as parameters to heat, so a fully automated deployment of various versions can be done without manual intervention.
> Specify version

- README.md
- environment.yml
- stack-single.yml
- stack.yml
- templates/stack.yml.j2
This allows to pass a parameter drives_vdx: true, which causes the automation to replace sdX with vdX in the host_vars inventory.
Note that I consider this an intermediate solution.
For the final solution, we need to discuss how to handle defaults/auto-detection/specification of disk names and NIC names.
(Note that NIC names are the more tricky piece!)
Options:
1. Try to autodetect everything. This should work reasonably well for disks, but there's no 100% safe way to detect the order of the network interfaces correctly. (We can probably guess 95% correctly though ... but specific clouds may actually have special high-perf NICs that we can't use then.)
2. Allow user to specify the disk and NIC names in the environment.yml.
3. Combine both by defaulting to an auto-detection allowing to …
> Drives vdx

- environments/ansible.cfg
It is useful to see deprecation warnings on the testbed.
> ansible: enable deprecation warnings

- environments/kolla/files/overlays/cloudkitty.conf
Required because of missing backport of https://review.opendev.org/#/c/699253/.
Can be reverted after the merge of https://review.opendev.org/#/c/725537/.
> Fix cloudkitty

- docs/source/overview.rst
- environments/kolla/configuration.yml
Ussuri will be the default of the testbed later.
Closes #200
> Add ussuri to the list of supported OpenStack releases

- heat/Makefile
- terraform/Makefile
We have a neat watch target in the heat Makefile, pulling the log file from the manager node, so we can follow the deployment (without accessing ARA).
Replicate this in the terraform framework.
As we need to parse the output to detect the completion (no wait condition here), we add a few more improvements:
- colorize the output (if COLORTERM=1)
- output all lines from the log
These improvements have been backported to the heat Makefile as well.
> watch target for terraform Makefile

- environments/custom/playbook-bootstrap-ceph-dashboard.yml
A restart of the ceph manager services is required to really change the dashboard
port.
The admin create user task should not fail when the admin user already exists.
> custom: fix the bootstrap-ceph-dashboard playbook

- environments/custom/playbook-wireguard.yml
Errors are ignored because the kernel module may not be available
after initial installation until after a reboot.
> custom: ignore Wireguard service start errors

- environments/ceph/configuration.yml
- environments/configuration.yml
00000000-0000-0000-0000-000000000000 is not a valid fsid.
> Use 11111111-1111-1111-1111-111111111111 as ceph fsid

- inventory/20-roles
- inventory/50-kolla
> inventory: by default place storage service on the control nodes

- docs/source/deployment.rst
the old one is orphaned and setup a new learn url
> update terraform learn link

- environments/configuration.yml
> Remove debops parameters

- environments/configuration.yml
> Remove network interfaces parameters

- environments/configuration.yml
> Remove timezone parameter

- environments/configuration.yml
> Remove cockpit parameters

- environments/configuration.yml
> Remove chrony parameters

- environments/configuration.yml
> Remove operator parameters

- terraform/Makefile
With the CONFIGURATION parameter it is possible to define the branch
of the configuration repository.
> Add CONFIGURATION parameter to the Makefile

- terraform/Makefile
The parameter can be used to specify the instance from which the
console log should be output. By default from the manager.
> terraform: add CONSOLE parameter to Makefile

- terraform/manager.tf
- terraform/nodes.tf
[   19.843510] cloud-init[835]: 2020-09-23 18:00:52,071 - schema.py[WARNING]: Invalid config:
[   19.848495] cloud-init[835]: write_files.0.permissions: 384 is not of type 'string'
[   19.852165] cloud-init[835]: write_files.1.permissions: 384 is not of type 'string'
...
> terraform: fix cloud init permissions

- terraform/Makefile
Makefile:27: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.
> terraform: fix copy & paste syntax issue in Makefile

- .github/workflows/deploy-daily-citycloud.yml
- .github/workflows/validate-terraform.yml
> github: drop terraform 0.12.9 and use 0.13.4

- docs/source/notes.rst
- inventory/10-custom
Without a 3rd ceph monitor node an upgrade is not possible.
> Enabled testbed-node-2 by default

- docs/source/deployment.rst
> docs: document the use of a different cloud provider name

- scripts/deploy_openstack_services_basic.sh
- scripts/deploy_openstack_services_extented.sh
DNSaaS is required by Gardener.
Closes #474
> Deploy designate as basic service

- terraform/Makefile
This uses the handy ?= syntax in make.
Likewise: Simplify setting OS_CLOUD.
> Allow passing ENVIRONMENT via environment ;-)

- terraform/nodes.tf
> Avoid terraform 0.11 interpolation syntax.

- terraform/neutron.tf
This is the same, but not all versions of neutron recognize vrrp.
This is required for OTC, but is harmless elsewhere.
> Use protocol 112 instead of vrrp.

- docs/source/deployment.rst
- terraform/Makefile
- terraform/environments/betacloud.tfvars
- terraform/environments/citycloud.tfvars
The overrides are controlled by comments in the envinroment files
now. You can add # override:XXXX in the environments files to include
overrides/XXXX_override.tf into your deployment.
This is used by betacloud and citycloud (neutron_availability_zone_hints)
and will be used by otc (neutron_router_enable_snat).
> Generalize override mechanism.

- docs/source/deployment.rst
Co-authored-by: Arvid Requate <requate@univention.de>
> docs: cloudprovider should be cloud_provider

- environments/custom/playbook-fetch-ceph-keys.yml
> custom: do not write ceph keys to glance-api directory

- terraform/minio.tf.disabled
> terraform: fix syntax of minio.tf.disabled

- inventory/host_vars/testbed-manager.osism.test.yml
- inventory/host_vars/testbed-node-0.osism.test.yml
- inventory/host_vars/testbed-node-1.osism.test.yml
- inventory/host_vars/testbed-node-2.osism.test.yml
> inventory: use node_id only for the network configuration

- inventory/host_vars/testbed-manager.osism.test.yml
- inventory/host_vars/testbed-node-0.osism.test.yml
- inventory/host_vars/testbed-node-1.osism.test.yml
- inventory/host_vars/testbed-node-2.osism.test.yml
> inventory: use node_id only for the network configuration (pt. 2)

- environments/ansible.cfg
Mitogen plugins have been removed from Ansible containers.
> Remove commented mitogen sample configuration

- docs/source/overview.rst
> docs: add pacific to the list of supported ceph releases

- docs/source/deployment.rst
- terraform/environments/otcbms.tfvars
> Add OTC documentation and use eu-de-01 as default zone for OTC BMS

- environments/custom/files/testbed_network_devices.fact
> Always use vxlan0 as provider network in testbed_network_devices.fact

- environments/ceph/configuration.yml
- scripts/003-ceph-services.sh
Setting auth_allow_insecure_global_id_reclaim to false breaks old ceph clients.
(glance-api)[glance@testbed-node-0 /]$ ceph -k /etc/ceph/ceph.client.glance.keyring -n client.glance -s
2021-06-28T17:48:09.215+0000 7efcd2ffd700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]
2021-06-28T17:48:09.231+0000 7efcd37fe700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]
[errno 13] RADOS permission denied (error connecting to the cluster)
> ceph: do not apply workarounds

- environments/kolla/configuration.yml
This reverts commit db63ac2e0a85b47e6c047807b90b58bfd6a80a2e.
> Revert "kolla: do not enable sanity checks by default"

- environments/custom/files/testbed_ceph_devices.fact
- environments/custom/files/testbed_ceph_devices_all.fact
- environments/custom/playbook-facts.yml
> custom: use hwinfo instead of lsblk to find available block devices

- terraform/environments/otcbms.tfvars
There are very few BMS instances in the OTC. Therefore, the
number used must be reduced.
> terraform: reduce the number of BMS nodes on the OTC to 3

- terraform/Makefile
> terraform: set default openstack version to wallaby

- environments/openstack/playbook-bootstrap-basic.yml
Amphora image is not required by OVN provider.
> Use OVN Octavia provider

- docs/source/overview.rst
> docs: fix default ceph version

- docs/source/usage.rst
- environments/kolla/configuration.yml
- scripts/007-openstack-services-extented.sh
There are no plans to offer the Magnum service in OSISM. Gardener should be used instead.
> Do not enable magnum by default

- environments/ceph/configuration.yml
Signed-off-by: Uwe Grawert <grawert@b1-systems.de>
> Fix role name typo in Ceph rgw configuration

- terraform/files/node.yml
Signed-off-by: Mathias Fechner <mathias.fechner@plusserver.com>
in ovn context their is strange behavior (can't install  packages, in cause of missing user dragon)
in new sequence  it works
> Move Operator role as 1st operation in Bootstrap node - pt. 2 Section

- terraform/manager.tf
--------------cut-----------
2021-11-15 14:53:25,268 - schema.py[WARNING]: Invalid config:
write_files.9.permissions: 448 is not of type 'string'
write_files.10.permissions: 448 is not of type 'string'
write_files.11.permissions: 448 is not of type 'string'
--------------cut-----------
> - fix cloud-init WARNING during bootup

- environments/kolla/configuration.yml
The upstream default has changed from nova to cinder.
We will stay with nova for now.
> kolla: use nova as nova ceph user

- environments/ceph/configuration.yml
Was accidentally removed with 3ac55e4645e582061a50ea244390d82a7c60821e.
> ceph: re-add openstack_config

- inventory/group_vars/testbed-managers.yml
- inventory/group_vars/testbed-nodes.yml
When running inside a virtualized environment, docker-compose needs to
be told the smaller MTU for each container it creates.
Closes: #912
> Set docker_network_mtu according to testbed environment

- scripts/001-helper-services.sh
It is also part of 002-infrastructure-services-basic.sh.
> Remove homer from 001-helper-services.sh

- terraform/variables.tf
With 30GB, we have some room for addtl. containers and logs.
> Base install is ~20GB on mgr and nodes, need more space.

- netbox/playbook-init.yml
- netbox/playbook-rack-1000.yml
Since we use the Netbox internally with Traefik and self-signed
certificates, we do not validate them.
> netbox: do not validate certs

- terraform/main.tf
HCP currently only offers 1.0.9.
Partly revert of 384ef2d2b5bdea7744e80c839bde9fa5046ce77e.
> Require terraform 1.0.0 because of HCP

- netbox/playbooks/rack-1000.yml
> netbox: add managed-by-osism tag to testbed-switch-0

- environments/configuration.yml
This parameter is required by environments/manager/run.sh
> Add missing operator_user

- environments/kolla/configuration.yml
We want to deprecated and remove them, as they are not tested in the
upstream CI and there are regressions in Xena, so stop running them
completely.
> Stop running kolla sanity checks #1064

- inventory/group_vars/testbed-managers.yml
- inventory/group_vars/testbed-nodes.yml
Since we use older versions of Ansible in ceph-ansible and
partly in kolla-ansible it is currently not possible to use
the ipaddr module anymore.
The module can be used again if we use Ansible >=4.0.0
everywhere.
> inventory: do not use ipaddr

- docs/source/usage.rst
- environments/kolla/configuration.yml
- scripts/002-infrastructure-services-basic.sh
etcd is not integrated anywhere and can be disabled.
> Do not deploy etcd

- contrib/check_infrastructure_services.sh
The first redis slave can be either of the two other nodes, split the
expected response pattern so that it matches both variants.
> Fix redis check

- docs/source/usage.rst
There are security concerns about Tailscale.
Accordingly, it is removed again.
> docs: remove tailscale

- environments/openstack/playbook-bootstrap-basic.yml
- environments/openstack/playbook-bootstrap-ceph-rgw.yml
- environments/openstack/playbook-bootstrap-magnum.yml
- environments/openstack/playbook-bootstrap-refstack.yml
- replaced all os_tasks with the corresponding openstack.cloud tasks.
- used for other tasks ansible.builtin and community.general tasks
- Make all collections available
- This close issues#1100
> Use openstack.cloud tasks & FQCN tasks

- terraform/files/manager.sh
This will solve the following warning:
dpkg-preconfigure: unable to re-open stdin: No such file or directory
Closes #1074
> terraform: DEBIAN_FRONTEND=noninteractive

- terraform/files/manager.sh
We do not wait for the completion of the connection. Accordingly,
it does not make sense to disable all ports directly.
> netbox: disable the ports on the switches after bootstrap

- docs/source/usage.rst
- environments/infrastructure/configuration.yml
- Change the http endpoints and use the https endpoints instead.
- This closes issues#1098
> Docs: Change http endpoints to https endpoints

- environments/custom/playbook-workarounds.yml
The apply leads to disconnections. Therefore, the manager
must be performed independently of the other nodes.
> Fix netplay apply in playbook-workarounds

- environments/kolla/files/overlays/galera.cnf
This is a leftover from the past and is no longer needed today.
> kolla: remove xtrabackup section from galera.cnf

- environments/kolla/configuration.yml
- environments/kolla/files/overlays/grafana/grafana.ini
Unified alerting has be enabled by config overlay file.
Signed-off-by: Uwe Grawert <grawert@b1-systems.de>
> Fix Grafana unified alerting

- terraform/outputs.tf
terraform: fixing deprecated warning
│
│   with local_file.id_rsa,
│   on outputs.tf line 9, in resource "local_file" "id_rsa":
│    9:   sensitive_content = openstack_compute_keypair_v2.key.private_key
│
│ Use the `local_sensitive_file` resource instead.
> terraform: fixing deprecated warning

- scripts/999-identity-services.sh
* in Xena loadbalancer must be used instead of haproxy
* The LDAP integration is currently not used in the testbed,
so it can be removed for the moment and reactivated later
Closes #1143
> Fix deploy-identity

- environments/kolla/files/overlays/heat.conf
No longer needed since the self-signed internal CA can now
be cleanly integrated at this point.
> kolla: remove custom heat.conf

- terraform/main.tf
The resource type local_sensitive_file is only available
from version 2.2.
Closes #1167
> terraform: use hashicorp/local >= 2.2

- .github/renovate.json
- Add renovate for the requirements.txt to fix the Sphinx-version issues.
- Partly osism/issue#155
> Add auto-renovate for the requirements.txt in docs

- environments/ceph/configuration.yml
- environments/kolla/files/overlays/keystone/federation/oidc/attribute_maps/oidc_attribute_mappingId1.json
- environments/openstack/playbook-bootstrap-basic.yml
- environments/openstack/playbook-bootstrap-refstack.yml
The `_member_` role is no longer being used anywhere, drop all
references to it.
Closes #1180
> Drop old "_member_" role

- environments/kolla/files/overlays/cinder.conf
- environments/kolla/files/overlays/nova/nova-compute.conf
- environments/openstack/playbook-bootstrap-basic.yml
enable in cinder.conf  and nova-compute.conf key manager barbican
enable a creation tasks for cinder volume type luks
> testbed: Enable customer facing disk encryption in testbed

- environments/openstack/playbook-bootstrap-ceph-rgw.yml
- environments/openstack/playbook-bootstrap-refstack.yml
- Fix the wrong ansible module: openstack.cloud.identity_role to the right one: openstack.cloud.role_assignment
> Fix wrong openstack.cloud ansible modules

- docs/source/deployment.rst
- scripts/009-openstack-services-baremetal.sh
- scripts/set-openstack-version.sh
Wallaby was still left in a few places. It should be Xena everywhere.
Related to #1206
> Use xena release everywhere

- terraform/scripts/cleanup.py
flake8 2.9.0 introduced E275, insisting on whitespace around keywords.
This affects the use of "assert" and "raise" in particular, which both
are statements, not functions, so we need to amend our code accordingly.
> Fix lint failure with new flake8

- environments/configuration.yml
> Remove ceph_share_directory

- environments/kolla/configuration.yml
- environments/kolla/files/overlays/nova/nova-compute.conf
nova_compute_virt_type is now a default and is set to kvm by default.
> kolla: remove nova_virt_type

- terraform/files/manager.sh
May be reverted later. For the moment, there is no other way.
> kolla: use qemu @ OTC

- environments/kolla/secrets.yml
This variable was added to kolla in the yoga cycle[0]. Since we don't
actually use this anywhere in the testbed, just add an empty key in
order to make ansible happy.
[0] https://review.opendev.org/c/openstack/kolla-ansible/+/835200
Closes: #1299
> Add neutron_ssh_key secret to kolla environment

- scripts/001-helper-services.sh
- scripts/002-infrastructure-services-basic.sh
- scripts/003-ceph-services.sh
- scripts/004-openstack-services-basic.sh
- scripts/005-monitoring-services.sh
- scripts/006-infrastructure-services-extended.sh
- scripts/007-openstack-services-extended.sh
- scripts/008-openstack-services-additional.sh
- scripts/009-openstack-services-baremetal.sh
- scripts/100-refstack.sh
- scripts/999-identity-services.sh
With the change in [0], the "osism apply" commands will return an error
code if the execution exits with a failure. Make sure that our
deployment scripts actually stop in this case in order to make debugging
easier.
> Set bash scripts to exit on error

- environments/kolla/files/overlays/keystone/wsgi-keystone.conf
The override template that was introduced in #1097 uses a kolla variable
that was added only in Zed. Add the variable definition temporarily so
that we don't need to make the template version dependent.
> Fix missing variable in keystone deployment

- doc/source/notes.rst
The image has not been supported for some time.
> Remove osism-testbed image from the notes

- environments/openstack/playbook-bootstrap-basic.yml
The check whether a volume type exists was failing, fix the check and
the return code. Also remove a redundant check.
Related: #1286
> Fix the encrypted volume tests

- environments/openstack/playbook-bootstrap-basic.yml
Depending on the performance of the underlying cloud, the creation of a
loadbalancer may take a long time. Increase the timeout from the default
of 3 minutes to 10 minutes.
> Set higher timeout for loadbalancer creation

- scripts/001-helper-services.sh
- scripts/002-infrastructure-services-basic.sh
- scripts/004-openstack-services-basic.sh
- scripts/005-monitoring-services.sh
- scripts/006-infrastructure-services-extended.sh
- scripts/007-openstack-services-extended.sh
By using the new Wait feature, it is possible to perform some of
the steps in parallel rather than sequentially.
> Improve deployment speed (pt. 1)

- environments/kolla/configuration.yml
Disable the debugging logs for Libvirt as Libvirt writes a lot of logs
that are not of interest.
> Set nova_libvirt_logging_debug = no

- ansible/manager-part-0.yml
In preparation to Ubuntu 22.04 we need to change the python3-crypto package.
Python3-cryptography worked in a Testbed Testdeployment as well as Python3-crypto.
Closes osism/testbed#1291
Signed-off-by: Ramona Beermann <rautenberg@osism.tech>
> Change from Python3-crypto to Python3-cryptography

- doc/source/deployment.rst
- doc/source/usage.rst
- environments/manager/configuration.yml
- environments/manager/images.yml
- environments/openstack/playbook-bootstrap-basic.yml
- scripts/009-openstack-services-baremetal.sh
- scripts/set-openstack-version.sh
- terraform/Makefile
- terraform/variables.tf
> Bump default OpenStack version in terraform to yoga

- environments/custom/files/testbed_ceph_devices.fact
- scripts/check/100-ceph-services.sh
- terraform/customisations/default_custom.tf
- terraform/main.tf
- terraform/overrides/nodes_use_ephemeral_storage_override.tf
Enables the use of the testbed on environments where Cinder is not usable or Cinder should not be used.
> terraform: allow use of ephemeral storage

- terraform/environments/otc.tfvars
- terraform/main.tf
The d-flavors have enough block devices out of the box.
Also fixes a small syntax thing.
> terraform: do not attach volumes @ otc

- contrib/openstack-cli/README.md
- contrib/openstack-cli/clouds-public.yaml
- contrib/openstack-cli/clouds.yaml.example
- contrib/openstack-cli/secure.yaml.example
just some helpful pointers if someone wants to use the openstack cli outside of the testbed manager in combination with the wireguard VPN
> Openstack cli examples

- playbooks/deploy.yml
new version of ansible/jina won't accept stdout.split
ansible [core 2.12.5]
python version = 3.9.14 (main, Sep  6 2022, 23:16:16) [Clang 13.1.6 (clang-1316.0.21.2.5)] jinja version = 3.1.2
> ansible: syntax issue

- contrib/openstack-cli/clouds-public.yaml
I accidentally merged this with syntax issues.
> Fix yaml syntax in openstack-cli/clouds-public.yaml

- ansible/manager-part-0.yml
- ansible/manager-part-1.yml
ansible.posix.synchronize is now the common way in ansible
https://docs.ansible.com/ansible/latest/collections/ansible/posix/synchronize_module.html#
> Use ansible.posix.synchronize instead of ansible.builtin.synchronize

- .zuul.yaml
- playbooks/pre.yml
Sometimes the post cleanup doesn't get executed properly. This can happen for multiple reasons, cloud instability, terraform state inconsistency, job aborted.
Add a new task in the pre-phase of a new deployment that makes sure all possible remainders of a previous run are cleaned up.
> CI: Add cloud cleanup in pre phase

- .zuul.yaml
There seems to be some confusion regarding the shared use of the tenant we received for testing at pluscloudopen, disable the daily jobs until this is resolved.
> Disable PCO daily jobs

- doc/source/requirements.rst
There is no problem anymore when creating multiple private networks within OVHcloud. They fixed it.
Signed-off-by: Arnaud Morin <arnaud.morin@gmail.com>
> Update OVH information

- .zuul.yaml
The testbed-upgrade job hit the 4h limit quite often. Bump the timeout to 4:30 h in order to give it a chance to finish successfully.
> Bump timeout for upgrade job

- environments/kolla/files/overlays/nova.conf
The default value in the nova.conf template should be good enough.
> kolla: remove novncproxy_base_url

- environments/openstack/playbook-bootstrap-basic.yml
- scripts/deploy/300-openstack-services-basic.sh
The image for Octavia will not be managed with the OpenStack Image Manager as this will be managed later within a playbook for Octavia itself.
> Use the OpenStack Image Manager to manage payload images

- environments/configuration.yml
Disabling auditd in the testbed to significantly reduce waste of resources (in the context of CI).
> Disabled auditd

- environments/openstack/playbook-bootstrap-basic.yml
The role creator is required to be able to create encrypted volumes If this role is not assigned the following error happens inside the cinder-volume service:
Forbidden: Order creation attempt not allowed - please review your user/project privileges
> openstack: assgin creator role

- scripts/deploy/000-manager-service.sh
The stable release images are located in a subdirectory on harbor.services.osism.tech. In the case of a stable release, it is easier to take the images from quay.io than to adapt all paths to the images.
Closes osism/testbed#1455
> Use images from quay.io for stable releases

- scripts/deploy/000-manager-service.sh
The stable release images are located in a subdirectory on harbor.services.osism.tech. In the case of a stable release, it is easier to take the images from quay.io than to adapt all paths to the images.
Part of osism/testbed#1455
> Use images from quay.io for stable releases (pt. 2)

- environments/kolla/configuration.yml
This is a workaround for the missing parameter
om_enable_rabbitmq_high_availability in the defaults of the 4.2.0 release. The parameter is required at this point so that the 4.2.0 release can be used with the testbed.
> kolla: add om_enable_rabbitmq_high_availability

- scripts/000-pull-images.sh
This reverts commit b740f6b267bf824d002aa5de85b2db481d8deb59.
Does not work with older stable versions of the OSISM cli. Keep the old way for the moment.
> Revert "Use new --action argument to pull kolla images (#1447)"

- scripts/deploy/000-manager-service.sh
On harbor.services.osism.tech the images are located in the namespace kolla. On quay.io they are in the namespace osism.
> Fix docker namespace for stable OSISM kolla images

- .ansible-lint
- ansible/manager-part-0.yml
- ansible/manager-part-1.yml
- ansible/manager-part-2.yml
- ansible/manager-part-3.yml
- contrib/ansible/dns.yml
- contrib/ownca/create_manager.yml
- contrib/ownca/create_wildcard.yml
- environments/custom/playbook-keycloak-oidc-client-config.yml
- environments/manager/playbook-manager.yml
- environments/openstack/playbook-bootstrap-basic.yml
- environments/openstack/playbook-bootstrap-ceph-rgw.yml
- environments/openstack/playbook-bootstrap-images.yml
- environments/openstack/playbook-bootstrap-refstack.yml
- playbooks/deploy.yml
- playbooks/post.yml
- playbooks/pre.yml
- playbooks/upgrade.yml
- tox.ini
In order to be able to fix the testbed quickly, the Ansible lint rules were deactivated as much as required for a short time. This change reverts that.
Related to 565f95ba0d60a67edc94dca5e4ac68f0610da70c.
> Re-enable most ansible-lint rules

- environments/kolla/configuration.yml
Add missing ironic_dnsmasq_dhcp_ranges parameter.
> Fix ironic deployment in zed

- .zuul.yaml
- playbooks/upgrade.yml
This job will test the upgrade from our current ceph/openstack releases (pacific/yoga) to the next ceph/openstack releases (pacific/zed).
> zuul: add upgrade-next job

- contrib/nagios-plugins/check_galera_cluster
Sometimes wsrep_flow_control_paused can return a value in scientific notation that bc cannot handle, convert it to float.
[0] fridim/nagios-plugin-check_galera_cluster#4
> Update check_galera_cluster nagios plugin

- .zuul.yaml
- tox.ini
Activate zuul job ansible-lint
Partly osism/issues#395
Signed-off-by: Ramona Beermann <ramona.beermann@osism.tech>
> Transfer ansible-lint to zuul job

- scripts/check/200-infrastructure-services.sh
in testbed will monitoring-plugins  rollout a rpcbind which is not needed here
Closes osism/testbed/#1489
> change: monitoring-plugins-basic

- environments/manager/configuration.yml
According to https://ara.recordsansible.org/blog/2023/02/26/ benchmarking-ara-with-different-databases-and-python3.11-for fun-and-science/ ARA with MariaDB as backend is faster.
This way we also ensure that the MariaDB/ARA integration is working like expected.
Closes osism/issues#439
> Use mariadb as backend for ara

- environments/kolla/files/overlays/ceilometer/pipeline.yaml
ceilometer is not configured to use gnocchi as sink.
this PR fixes that
> fixes sending metrics also to gnocchi

- environments/ceph/configuration.yml
> ceph: use keystone port 5000 instead of 35357

- environments/infrastructure/configuration.yml
- scripts/deploy-manager.sh
The new wireguard role needs some options being set in the configuration in order to deploy the same setup as before.
Depends-On: https://github.com/osism/ansible-collection-services/pull/927
> Adapt wireguard config to modified role

- environments/custom/playbook-keycloak-oidc-client-config.yml
- environments/kolla/configuration.yml
- environments/kolla/files/overlays/keystone/wsgi-keystone.conf
Changes to use Authorization Code flow with PKCE in Keycloak for security reasons.
@matfechner 
https://github.com/SovereignCloudStack/issues/issues/293
> Use Authorization Code flow with PKCE in Keycloak OIDC federation

- doc/quickstart.md
- doc/requirements.md
- terraform/environments/huaweicloud.tfvars
Hi, we tried to install the test bed on Huaweicloud EU region and it worked. So updating the documentation to reflect the same. 
Thank you.
> add Huaweicloud as supported list of clouds for testbed.

- terraform/Makefile
I was told this is an issue in our log output, for example here:
https://logs.services.betacloud.xyz/periodic-daily/github.com/osism/testbed/main/testbed-deploy/75b3979/job-output.txt
this can be overridden by overwriting TF_CLI_ARGS
see the upstream docs for details:
https://developer.hashicorp.com/terraform/cli/config/environment-variables#tf_cli_args-and-tf_cli_args_name
if some subcommand does not support this feature, this is considered
a bug and should be reported, according to this message:
https://github.com/hashicorp/terraform/issues/15264#issuecomment-1158930479
Signed-off-by: Sven Kieske <kieske@osism.tech>
> remove colored output from terraform by default

- playbooks/pre.yml
- playbooks/templates/local.env.j2
This way we are no longer dependent on Terraform being present on the CI nodes and can determine the Terraform version via the job.
> Download terraform in pre playbook

- terraform/terragrunt.hcl
Quota exceeded for resources: The quota might be taken up by an ongoing cleanup, so a retry might be useful.
Error waiting for instance: Sometimes an instance does not come up correctly, a retry then makes sense.
> Add more retry rules in Terragrunt configuration

- Makefile
- playbooks/deploy.yml
- playbooks/upgrade-stable.yml
- playbooks/upgrade.yml
- scripts/bootstrap-services.sh
- scripts/bootstrap.sh
- scripts/bootstrap/300-openstack-services.sh
- scripts/deploy/300-openstack-services-basic.sh
- terraform/Makefile
This makes it possible to not run the bootstrap multiple times when using an upgrade job.
> Move the bootstrap from services to its own script

- environments/kolla/configuration.yml
- scripts/deploy/320-openstack-services-baremetal.sh
The virtualbmc service was included as a workaround to test Ironic for functionality within the testbed. In the future we will have access to real baremetal systems to perform real tests of Ironic. Therefore, the approach to use emulated baremetal systems within the testbed will not be pursued further. The deployment of Ironic continues to be tested in the testbed.
> Remove virtualbmc service

- terraform/customisations/default_custom.tf
- terraform/manager.tf
Sometimes it happens that the system time is not correct after a boot. This then leads to anomalies in the bootstrap process. For example, the mtime on certain files is incorrect as a result. To work around the problem in the testbed, Chrony is already deployed with cloud-init. Thus a correct system time is available directly after the boot even before the bootstrap process was executed.
$ stat /var/lib/apt/periodic/update-success-stamp
File: /var/lib/apt/periodic/update-success-stamp
Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: 801h/2049d	Inode: 69167       Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-05-12 10:26:37.609383906 +0000
Modify: 2023-05-12 10:36:46.308000000 +0000
Change: 2023-05-12 …
> Configure chrony with cloud-init

- ansible/manager-part-3.yml
- terraform/manager.tf
Causes conflicts with part 0 from the manager playbook.
Related to 75fd285e3e904070aed6674b22f147fe51560bea.
> Do not update packages with cloud-init on the manager

- scripts/bootstrap/300-openstack-services.sh
- scripts/check.sh
- scripts/deploy/100-ceph-services-basic.sh
- scripts/deploy/310-openstack-services-extended.sh
- scripts/upgrade/310-openstack-services-extended.sh
don't install skyline for osism < 5
also fix 2 minor shellcheck issues around variable quoting.
Signed-off-by: Sven Kieske <kieske@osism.tech>
> refactoring the osism version logic

- .zuul.yaml
Update to the rolling tag to always ensure that an update to the next release will be possible.
> zuul: update to the rolling tag

- environments/custom/playbook-keycloak-oidc-client-config.yml
- environments/kolla/files/overlays/keystone/wsgi-keystone.conf
[RFC  7636](https://datatracker.ietf.org/doc/html/rfc7636) says `If the client is capable of using "S256", it MUST use "S256"`. We have confirmed in the testbed that we can, so we should make this trivial switch.
> Use the S256 method for PKCE as prescribed by RFC

- doc/federation.md
SCS is able to be federate out to external IdP (https://github.com/SovereignCloudStack/issues/issues/182)
As part of the issue I added a small documentation on how to add a remote SSL certificate to the Keycloak truststore to allow Keycloak to resolve that certificate.
> Added documentation of how to add an SSL cert to keycloak truststore

- contrib/rally/rally.json
- contrib/rally/rally.sh
- Use https keystone URL
- Drop outdated workaround
> Fix rally testing

- ansible/manager-part-3.yml
- environments/infrastructure/configuration.yml
- inventory/group_vars/testbed-nodes.yml
- scripts/000-pull-images.sh
- scripts/deploy-manager.sh
- scripts/deploy/000-manager-service.sh
This change adds a squid proxy that allows only whitelisted traffic to every component, that is set to use this proxy.
partly #1439 
> Enable proxy

- environments/infrastructure/configuration.yml
- scripts/deploy/210-infrastructure-services-extended.sh
The new approach with Squid etc. means that Nexus will no longer be needed in the future.
> Remove nexus deployment

- ansible/manager-part-3.yml
The images from the manager can be downloaded in the background without actively waiting for them.
A timeout of 10 minutes is fine. Depending on how many CI deployments are running in parallel, it may take a while until the download is completed.
> Do not wait for the pull of the manager images

- environments/custom/configuration.yml
- environments/custom/playbook-keycloak-oidc-client-config.yml
- environments/kolla/files/overlays/keystone/wsgi-keystone.conf
Quick fix to the LOGOUT found on a fresh deploy of the testbed.
Someone has to check if the copy of the certificate into the container and the adition to the keycloak keytool is done in the correct "ansible" way.
> logout redirect url issue

- terraform/customisations/default_custom.tf
- terraform/environments/ci.tfvars
- terraform/environments/regiocloud.tfvars
- terraform/variables.tf
With the volume_type variable it is possible to set the volume type of the volumes used for ceph. By default the __DEFAULT__ volume type is used.
> terraform: add support for volume types

- .zuul.yaml
We want to run these jobs only after a core reviewer has looked at the PR and attached the "zuul" label.
> Use label pipeline for deployment jobs

- terraform/environments/ci.tfvars
This way we do not have unnecessary traffic on the NVMe SSD pool.
> zuul: use local storage for CI jobs

- playbooks/post.yml
For whatever reason, the cleanup-post play is not executed. Merge the cleanup play with the post play so that it is always cleaned up.
> zuul: merge cleanup & post play

- environments/kolla/configuration.yml
- environments/kolla/files/overlays/manila/ceph.conf
- releasenotes/notes/manila-cephfs-28b94dbdb39289c0.yaml
> Use CephFS as filesystem for OpenStack Manila

- environments/manager/hosts
Required to be able to use the osism-update-docker script.
> manager: add hosts files

- terraform/scripts/cleanup.py
On OpenTelekomCloud EIPs needs to be cleaned up before routers, otherwise router cleanup will fail.
> Cleanup FloatingIPs before routers

- environments/kolla/configuration.yml
Only required when working with the Neutron L3 agent.
> kolla: remove enable_neutron_agent_ha parameter

- ansible/manager-part-1.yml
- ansible/manager-part-3.yml
- environments/configuration.yml
quay.io is often slow or unreliable. We are starting to switch back to our own registry.
> Get manager images from osism.harbor.regio.digital

- ansible/manager-part-0.yml
Necessary if the stable images of Cloud init are imported on the CI.
> Wait up to 10 minutes until boot of manager finished

- environments/configuration.yml
- releasenotes/notes/do-not-pull-images-with-docker-compose-service-21067abc864e3fb3.yaml
This reverts commit 468133c87c553904ac2b4fb4d4b54c58b10c858b.
Does not work at the moment because of a incorrectly implemented health check in some osism.services roles.
> Revert "Do not pull images with docker-compose service (#1923)"

- environments/kolla/files/overlays/haproxy/services.d/haproxy.cfg
> kolla: only use the active ceph-mgr service for the dashboard

- scripts/000-pull-images.sh
Sometimes the registry throws an error. Running it again fixes the problem.
> Retry pull of images up to 2 times

- environments/custom/playbook-pull-images.yml
This avoids problems with the newly introduced pass-through cache.
> PUll images sequentially

- .ansible-lint
- environments/kubernetes/configuration.yml
- environments/kubernetes/files/nginx.yml
- environments/kubernetes/images.yml
- environments/kubernetes/playbook-nginx.yml
- environments/kubernetes/secrets.yml
$ osism apply -e kubernetes nginx
$ kubectl get pods -n nginx
NAME                    READY   STATUS    RESTARTS   AGE
nginx-f7f5c78c5-crhnf   1/1     Running   0          2m28s
nginx-f7f5c78c5-tjf6r   1/1     Running   0          2m28s
nginx-f7f5c78c5-qbqjz   1/1     Running   0          2m28
$ kubectl get services -n nginx
NAME    TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)        AGE
nginx   LoadBalancer   10.43.84.203   192.168.16.100   80:30612/TCP   2m46s
$ curl -I http://192.168.16.100
HTTP/1.1 200 OK
Server: nginx/1.25.3
> Add kubernetes environment with sample service

- environments/openstack/clouds.yml
- scripts/bootstrap/300-openstack-services.sh
The osism.services.openstack_health_monitor role is not functional at the moment.
The openstack health monitor can be debployed with https://github.com/SovereignCloudStack/openstack-health-monitor/tree/main/startup after the testbed deployment finished.
> Do not deploy the openstack-health-monitor

- .zuul.yaml
Deploy OpenStack 2023.2 & Ceph Quincy with latest OSISM.
> zuul: add testbed-deploy-next job

- .zuul.yaml
Deploy OpenStack 2023.1 & Ceph Quincy with latest OSISM and upgrade to OpenStack 2023.2 & Ceph Quincy with latest OSISM.
> zuul: add testbed-upgrade-next job

- .zuul.yaml
abstract from now on always as a prefix for better visibility.
> zuul: use abstract-testbed-deploy

- scripts/deploy/200-infrastructure-services-basic.sh
7.0.0b will still contain various errors.
Related to 294af384a1944c2c5b15c090dd58db0c68c83688
> Deploy kubernetes/keycloak only as of 7.0.0c

- environments/openstack/playbook-test-identity.yml
As we never have the roles for octavia and barbican on the identity testbed, they will not be used for the test-identity play.
> Fix the test-identity play

- environments/kolla/configuration.yml
- scripts/deploy-identity-services.sh
- scripts/deploy/200-infrastructure-services-basic.sh
Can only be used from OSISM 7.0.0 onwards.
> Disable keystone federation by default

- environments/ceph/configuration.yml
No longer needed as we prepare the OSDs with our own plays.
> ceph: remove osds_per_device parameter

- terraform/Makefile
The `terraform/Makefile` uses the `open` command to show the documentation of OSISM service endpoints. On linux the equivalent command would be `xdg-open`.
> Use `xdg-open` on linux

- scripts/upgrade/300-openstack-services-basic.sh
In the testbed, the service was only added with OSISM 7.0.0. It is therefore necessary to check in advance whether the service is already available. If not, a deployment must be carried out instead of an upgrade.
> When doing an upgrade deploy magnum if magnum is not yet there

- environments/ceph/configuration.yml
We only have a limited number of OSDs. Therefore, increase the number of PGs per OSD in the testbed.
Error ERANGE:  pg_num 64 size 3 for this pool would result in 275 cumulative PGs per OSD (1650 total PG replicas on 6 'in' root OSDs by crush rule) which exceeds the mon_max_pg_per_osd value of 250
> ceph: increase map pgs / osd to 512

- environments/ceph/configuration.yml
We only have a limited number of OSDs. Therefore, increase the number of PGs per OSD in the testbed.
Error ERANGE:  pg_num 64 size 3 for this pool would result in 275 cumulative PGs per OSD (1650 total PG replicas on 6 'in' root OSDs by crush rule) which exceeds the mon_max_pg_per_osd value of 250
This also reverts a5f70f8cb48d4b4ccf0798690d3de8a33776595c
> ceph: decrease default num of pgs per pool to 32

- environments/kolla/configuration.yml
We use debug logs for all OpenStack services on the testbed. Therefore, a lot of logs are collected in a short time. We therefore set the retention time of OpenSearch to a very low value to prevent the storage from running full.
Part of osism/testbed#2112
> Set soft & hard retention time for OpenSearch to 1d

- ansible/check-local-versions.yml
ansible pip package with version 9.4.0 is installed in requirements.txt, but it is only compatible with python >= 3.10 (https://pypi.org/project/ansible/)
> Increase python3.10 version requirement to due 'ansible' package

- terraform/clouds-public.yaml
The environment `regiocloud-fast` was renamed to `regio-fast`. The profile in `terraform/clouds-public.yaml` needs to be changed aswell.
> Rename regiocloud-fast in clouds-public.yaml

- ansible/manager-part-2.yml
- environments/configuration.yml
The Docker CLI version must also be pinned as the default of the Docker CLI version was only recently set to the Docker version itself. If the Docker CLI version has not been pinned, problems may occur if only the Docker CLI is downgraded/upgraded after the initial deployment of Docker.
> Pin docker_cli_version

- ansible/manager-part-0.yml
- environments/configuration.yml
The correct package name is linux-generic-hwe-22.04 on Ubuntu 22.04 and linux-generic-hwe-24.04 on Ubuntu 24.04.
> Make linux-generic-hwe independent of the Ubuntu version used

- .ansible-lint
> ansible-lint: do not mock kubernetes.core.k8s

- ansible/manager-part-0.yml
Can be reverted when the "Error while fetching server API version: Not supported URL scheme http+docker" is fixed in requests. There are just various releases of requests that were yanked one after the other.
> Pin requests for initial manager service deployment

- ansible/manager-part-0.yml
This reverts commit ec64acded3d2084d4136631538ab428145dbeb6b.
Closes osism/testbed#2217
> Revert "Pin requests for initial manager service deployment (#2216)"

- environments/kolla/configuration.yml
- environments/kolla/group_vars/keystone.yml
- scripts/deploy-identity-services.sh
- scripts/deploy/200-infrastructure-services-basic.sh
- scripts/deploy/300-openstack-services-basic.sh
- scripts/upgrade/300-openstack-services-basic.sh
The Keycloak OIDC client play and the SCS keycloak image are currently not working reliably. We are therefore moving this part to a dedicated testbed so that the general testbed deployment works independently.
> Prepare dedicated identity testbed for Keystone/Keycloak integration

- ansible/manager-part-3.yml
The "Use insecure glance configuration" task should not overwrite the existing glance-api.conf file. It should only add additional configuration to the existing glance-api.conf file.
> Fix "Use insecure glance configuration" task

- Makefile
- terraform/Makefile
With the name Makefile parameter CLOUD_ENVIRONMENT it is possible to overwrite the used cloud profile. By default ENVIRONMENT is used.
> Make it possible to overwrite the used cloud environment

- environments/custom/playbook-workarounds.yml
This way we ensure that the vxlan interfaces are available without a reboot.
> custom: start the workaround services

- scripts/check/100-ceph-services.sh
The Ceph validate plays are only usable with Docker at the moment. On CentOS we use Podman for the Ceph deployment and cannot use the Ceph validate plays at the moment.
> Do not use the Ceph validate plays on CentOS

- terraform/scripts/cleanup.py
Avoid deleting attached FIPs, better port filtering.
The filter in the search_floating_ip() statement does not do what it is
supposed to. Instead skip if there is a fixed_ip_address.
For port cleanup, provide better logic:
* Delete port unconditionally if it's name matches the prefix
* Keep it unconditionally if it has a name that does not match
* IF we have a list of IPADDR strings the beginning of the ip
addresses will be matched against the IPADDR strings; delete
if there is a match, do not delete if there is no match.
Always match, if no IPADDR filter is passed.
The filtering can be used to ensure we only delete IP addresses from
IP ranges in subnets that we have created. This improves coexistence
with other infrastructure in the smae project.
(If you can, avoid coexistence, though.) …
> Avoid deleting attached FIPs, better port filtering.

- environments/infrastructure/configuration.yml
Sometimes they are not yet compatible with latest. In the testbed we should only use plugins that also worked in the CI of the netbox role.
> infrastructure: do not enable extra plugins

- .zuul.yaml
The nutshell deployment is usable for OSISM >= 8.0.0.
> zuul: add deploy-stable-in-a-nutshell jobs

- environments/kolla/files/overlays/magnum.conf
this allows magnum clusters to be created in testbed "full deploy" after executing:
```
/opt/configuration/scripts/bootstrap/301-openstack-octavia-amhpora-image.sh && \
/opt/configuration/scripts/bootstrap/302-openstack-k8s-clusterapi-images.sh
```
```
openstack --os-cloud admin coe cluster template create \
--coe kubernetes \
--image <clusterapi-image-id> \
--external-network public \
--dns-nameserver 8.8.8.8 \
--master-lb-enabled \
--master-flavor SCS-2V-4-20s \
--flavor SCS-2V-4-20s \
--network-driver cilium \
--docker-storage-driver overlay2 \
--volume-driver cinder \
--label kube_tag=v1.30.4 --label keystone_auth_enabled=false \
k8s-v1.30.4;
```
```
openstack --os-cloud admin coe cluster create --cluster-template k8s-v1.30.4 \
--master-lb-enabled \
--master-count 3 \
--node-count 3 \ …
```
> disable verify_ca for magnum related openstack apis

- environments/manager/configuration.yml
Sometimes they are not yet compatible with latest. In the testbed we should only use plugins that also worked in the CI of the netbox role.
Related to 3acd3ef806aec0f3059f0fad14aa108c8f1c8c7d
> manager: do not enable extra netbox plugins

- ansible/manager-part-0.yml
Required to resolve "System is booting up. Unprivileged users are not permitted to log in yet. Please come back later. For technical details, see pam_nologin(8)"
> Retry the "Check /var/lib/cloud/instance/boot-finished" task

- inventory/20-roles
- scripts/enable-resource-nodes.sh
Related to 3a94d651776fb6ba7b85767b489116265101bbd3
> Do not use testbed-node-[0-2] as k3s nodes in a small testbed

- environments/infrastructure/configuration.yml
Fix timeout of manager deployment due to low docker compose healthcheck `start_period`.
> Increase netbox start period

- environments/kolla/configuration.yml
The testbed is unstable after changing the defaults. Test whether it is due to durable queues.
> Disable rabbitmq durable queues

- scripts/deploy/000-manager-service.sh
Required because of e6f916e7aefe2ff2e3a5c3cf8a5670b33cd1f1f0
> Apply resolvconf before sshconfig

- environments/infrastructure/configuration.yml
> infrastructure: remove squid_allowed_addresses parameter

- environments/custom/playbook-cinder-driver-dm-clone.yml
- environments/kolla/configuration.yml
- environments/kolla/files/overlays/cinder/cinder-volume.conf
- environments/openstack/playbook-bootstrap-basic.yml
- inventory/99-overwrite
- inventory/group_vars/testbed-nodes.yml
- scripts/deploy/200-infrastructure-services.sh
- scripts/deploy/300-openstack-services.sh
- scripts/upgrade/200-infrastructure-services.sh
* Create volume group on third supplied block device
* Checkout cinder dm-clone driver
* Add compute nodes to `storage` group
* Deploy cinder lvm backend and iscsi containers
* Add and enable local backend using dm-clone driver
* Add volume type for local backend
> Add tech preview of local storage in cinder

- .ansible-lint
The netbox playbooks are failing ansible-lints checks for some time now, but the exact cause for that is unclear, let's exclude them.
> ansible-lint: exclude netbox playbooks

- environments/kolla/configuration.yml
The ironic_prometheus_exporter is broken right now and cannot be scraped. The error is in the ironic-conductor ([1]) while fetching the metrics.
[1]
2024-12-07 10:18:15.321 7 ERROR ironic.conductor.manager [-] An unknown error occurred while attempting to collect sensor data from within the conductor. Error: Metrics action is not supported. You may need to adjust the [metrics] section in ironic.conf.: ironic_lib.exception.MetricsNotSupported: Metrics action is not supported. You may need to adjust the [metrics] section in iro nic.conf.
2024-12-07 10:18:15.321 7 ERROR ironic.conductor.manager Traceback (most recent call last):
2024-12-07 10:18:15.321 7 ERROR ironic.conductor.manager   File "/var/lib/kolla/venv/lib/python3.10/site-packages/ironic/conductor/manager.py", line 2681, in …
> Disable ironic_prometheus_exporter

- environments/kolla/configuration.yml
Disabling ironic prometheus exporter will happen as a global default in osism. It is not required here.
This reverts commit cd26c5afc35750120ac5177852f881c872322104.
> Revert "Disable ironic_prometheus_exporter (#2557)"

- ansible/manager-part-1.yml
- environments/custom/files/testbed_network_devices.fact
- environments/custom/playbook-facts.yml
- playbooks/managerless/pre.yml
- scripts/deploy-manager.sh
The `netifaces` library has been unmaintained for more than three years [1] and now been removed from `openstacksdk` [2].
The custom fact to match interfaces to networks is rewritten and all dependencies on `netifaces` removed.
[1]
https://github.com/al45tair/netifaces
[2]
https://review.opendev.org/c/openstack/openstacksdk/+/931588
> Remove dependency on netifaces

- environments/kolla/files/overlays/neutron.conf
Set the default availability zone for neutron to the configured `nova` zone. OVN external ports require the availablity zone to be set if zones are configured. Failure to do so will result in an empty `ha_chassis_group`. Setting the zone via `availability-zone-hint` is not supported by ansible module `openstack.cloud.network`.
Part of https://github.com/osism/issues/issues/1196
> Set default neutron availability zone

- inventory/group_vars/all/vxlan.yml
- inventory/group_vars/testbed-control-nodes.yml
- inventory/group_vars/testbed-managers.yml
- inventory/group_vars/testbed-nodes.yml
- scripts/deploy/000-manager.sh
Use the network role to create vxlans. This is mostly a drop-in
replacement with the exception that it does not add IP addresses to the
`vxlan0` interface except for the manager node. Since the vxlan is used
as a neutron external network attached to an openvswitch bridge on all
nodes except for the manager, the address is unusable there anyway
Part of https://github.com/osism/issues/issues/1196
Depends on https://github.com/osism/ansible-collection-commons/pull/749
Depends on https://github.com/osism/ansible-collection-commons/pull/754
> Use network role to create vxlans

- environments/custom/files/baremetal-tenks-override.yml
- environments/custom/playbook-baremetal-bootstrap.yml
- environments/custom/playbook-baremetal-prepare.yml
- environments/custom/templates/ironic-interface.service.j2
- environments/kolla/configuration.yml
- environments/kolla/files/overlays/ironic/ironic-conductor.conf
- scripts/deploy-baremetal.sh
Add a deployment scenario, where `testbed-resource-nodes` are used to
provide virtual machines for baremetal deployment.
Virtual baremetal machines are created using `tenks` ([1]), which may
later also be used to register baremetal nodes and create matching
flavors.
The network `vxlan0`, which serves as an external network in ordinary
deployments is used as a provider network conected to the virtual
baremetal. Additionally an out-of-band network is created to manage the
machines via virtual BMC.
Since routing to the API network did not seem to work during PXE
booting, ports are created for the ironic tftp and httpd services and
connected to the control plane in a similar way to what is done in kolla
for octavia amphora management networks ([2]). Routing to the ironic API
during callback …
> Add baremetal deployment

- inventory/group_vars/testbed-managers.yml
- inventory/group_vars/testbed-nodes.yml
- scripts/deploy/000-manager.sh
Something is broken with the vxlan netdev approach. The created vxlan is not usable for the simulation of the public network.
> Use vxlan networkd dispatcher script for the moment

- inventory/group_vars/testbed-managers.yml
- inventory/group_vars/testbed-nodes.yml
- scripts/deploy/000-manager.sh
This reverts commit d013f0cbb53653e5b9aead5bcd4518a8960aa53e.
Fixed by osism/ansible-collection-commons#765
> Revert "Use vxlan networkd dispatcher script for the moment"

- ansible/manager-part-3.yml
- environments/custom/playbook-pull-images.yml
The images are not always required and therefore no longer need to be pulled in advance.
> Do not longer pull osism-netbox and heat images

- environments/custom/playbook-baremetal-bootstrap.yml
The subnet has an external gateway for connectivity of instances deployed in it.
The resulting default route received via DHCP on control nodes breaks their external connectivity and is therefore removed by a `dhclient` hook.
> Remove default route for ironic-boot device on control nodes

- ansible/manager-part-2.yml
- environments/configuration.yml
It actually leads to pretty large images without any benefit for us.
Related to a1ea9dbd63b28e627490bbe1f7035647bd0f8071 Related to aa744612f65f430bf2d9a00552fd733d105b2475
> Disable containerd image store on Docker Engine

- environments/manager/configuration.yml
Remove parameters that are set by default.
> manager: cleanup parameters of osism.commons.configuration

- scripts/deploy-baremetal.sh
Ceph takes a long time to deploy and using it is not central to the baremetal scenario.
Use the file backend for glance and do not deploy cinder and kolla-ceph-rgw.
> Disable ceph during baremetal scenario

- ansible/manager-part-0.yml
- scripts/manager-version.sh
This ways it's not necessary to install yq. yq is only required to extract the version of the manager.
Part of osism/testbed#2664
> Use awk instead of yq in scripts/manager-versions.h

- .zuul.yaml
Zuul has deprecated the "cleanup-run" parameter, this is to be replaced by "post-run" with the cleanup attribute set to true.
> Fix deprecated zuul syntax

- environments/custom/playbook-baremetal-netbox.yml
- environments/custom/templates/baremetal-netbox-device.yml.j2
Netbox 4.2 requires the mac addresses to be explicitly created and assigned to the device as primary address.
Additionally the naming of virtual baremetal devices in the netbox is changed and `--quiet` flag is used to find libvirt mac addresses.
> Fix MAC addresses in baremetal scenario

- .zuul.yaml
- scripts/deploy/000-manager.sh
We only use the Netbox in the bare metal testbed. To save time, we skip the initialisation in the normal testbed. For demos, initialisation can be done later with osism manage netbox.
> Remove netbox initialization from manager deployment script

- Makefile
- ansible/manager-part-3.yml
- environments/manager/configuration.yml
- terraform/Makefile
Introduces DEPLOY_MODE variable to control netbox enablement based on deployment type. Netbox is now enabled only for baremetal deployments while remaining disabled for manager-only deployments.
> Add deploy mode support for conditional netbox deployment

- scripts/deploy-manager.sh
Do not restart the old manager service `docker-compose@manager.service` on osism versions using the new `manager.service`.
This fixes a bug where applying the manager role would stop the manager service when trying to stop and disable the old manager service, which would be active due to the restart and issue a `docker-compose down`.
> Do not restart old manager service

- scripts/pull-images.sh
As we are still preparing the Ceph configuration before the deployment, we do not need to actively wait for the container images to be pulled.
> Pull images in background

- scripts/deploy-in-a-nutshell.sh
Required by kubernetes, not handled by nutshell.
> Deploy frr in deploy-in-a-nutshell.sh
