- README.md
- environments/infrastructure/configuration.yml
- scripts/deploy_infrastructure_services.sh
- stack-single.yml
- stack.yml
- templates/stack.yml.j2
> Add netdata

- README.md
- environments/kolla/configuration.yml
- stack-single.yml
- stack.yml
- templates/stack.yml.j2
> Add barbican

- README.md
- environments/kolla/configuration.yml
- stack-single.yml
- stack.yml
- templates/stack.yml.j2
> Add designate

- environments/custom/playbook-cronjobs.yml
- stack-single.yml
- stack.yml
- templates/stack.yml.j2
> custom: add playbook-cronjobs.yml

- README.md
- environments/openstack/clouds.yml
- environments/openstack/playbook-bootstrap-basic.yml
- environments/openstack/secure.yml
- inventory/host_vars/testbed-node-0.osism.local.yml
- inventory/host_vars/testbed-node-1.osism.local.yml
- inventory/host_vars/testbed-node-2.osism.local.yml
- scripts/deploy_openstack_services.sh
- stack-single.yml
- stack.yml
- templates/stack.yml.j2
> Add script to bootstrap the basic OpenStack environment

- README.md
Mention OS_CLOUD and more precise storage requirements.
(Local storage from the flavor is also storage ...)
Those two were unrelated, so I submit them separately.
> Minor doc improvements.

- environments/openstack/playbook-bootstrap-basic.yml
* [WARNING]: Module did not set no_log for update_password
* Add flavor tiny the hw_rng:allowed extra spec
> Fix two issues in bootstrap basic

- .gitignore
- Makefile
This prevents that already existing SSH keys on a system are affected.
> Makefile: save the ssh key in the local directory

- environments/kolla/configuration.yml
Replaced by https://review.opendev.org/#/c/713628/
> Remove rabbitmq_clusterer_version

- stack-single.yml
- stack.yml
- templates/stack.yml.j2
> Add Ceph RGW deployment to the stack templates

- README.md
- contrib/refstack/accounts.yaml
- contrib/refstack/refstack.sh
- contrib/refstack/tempest.conf
- environments/ceph/configuration.yml
- environments/openstack/playbook-bootstrap-refstack.yml
- stack-single.yml
- stack.yml
- templates/stack.yml.j2
> Add refstack to stack templates and fix some issues with refstack

- heat/Makefile
- terraform/Makefile
> Add 192.168.100.0/24 to sshuttle

- docs/source/overview.rst
- scripts/deploy_openstack_services_additional.sh
> kolla: deploy influxdb

- environments/kolla/secrets.yml
> Fix wrong barbican_crypto_key

- docs/source/networking.rst
- docs/source/usage.rst
- environments/custom/configuration.yml
- environments/custom/files/wireguard/client.conf
- environments/custom/playbook-wireguard.yml
- environments/custom/templates/wireguard/wg0.conf.j2
- heat/stack-single.yml
- heat/stack.yml
- heat/stack.yml.j2
- inventory/host_vars/testbed-node-0.osism.local.yml
- inventory/host_vars/testbed-node-1.osism.local.yml
- inventory/host_vars/testbed-node-2.osism.local.yml
- terraform/manager.tf
- terraform/neutron.tf
- terraform/nodes.tf
> Add wireguard

- environments/ceph/configuration.yml
> ceph: fix default pool size

- contrib/refstack/accounts.yaml
- contrib/refstack/refstack.sh
- docs/source/usage.rst
- environments/openstack/playbook-bootstrap-refstack.yml
This will fix the following test:
IdentityV3ProjectsTest:test_list_projects_returns_only_authorized_projects
> refstack: use dedicated projects

- docs/source/overview.rst
- environments/kolla/configuration.yml
- scripts/deploy_openstack_services_additional.sh
> Deploy manila

- inventory/host_vars/testbed-node-0.osism.local.yml
- inventory/host_vars/testbed-node-1.osism.local.yml
- inventory/host_vars/testbed-node-2.osism.local.yml
This reverts commit 00007eab2a5305cda36699f1cfa6dfd32aef027a.
> Revert "inventory: disable default docker network on the nodes (#183)"

- environments/ceph/configuration.yml
> ceph: enable dmcrypt

- environments/kolla/files/overlays/zun/zun-compute.conf
- inventory/group_vars/zun-compute.yml
- inventory/host_vars/testbed-node-0.osism.local.yml
- inventory/host_vars/testbed-node-1.osism.local.yml
- inventory/host_vars/testbed-node-2.osism.local.yml
> kolla: use kata container as zun default runtime

- environments/kolla/configuration.yml
This reverts commit e3bddaf4eb81f89b25de231d1690f432e6550e1b.
> Revert "kolla: enable osprofiler (#243)"

- environments/kolla/configuration.yml
> Use OVN starting with the Ussuri release

- playbooks/node.yml
> Deploy docker on the nodes during initial bootstrap

- terraform/manager.tf
> Install missing docker ansible roles (pt. 2)

- docs/source/deployment.rst
- terraform/environment-Betacloud.tfvars
- terraform/environment-CityCloud.tfvars
- terraform/environment-OVH.tfvars
- terraform/main.tf
- terraform/variables.tf
> terraform: add cloud_provider variable

- terraform/Makefile
> terraform: remove unused targets from the Makefile

- .github/workflows/syntax-rst.yml
- docs/source/deployment.rst
- docs/source/networking.rst
- docs/source/notes.rst
- docs/source/overview.rst
- docs/source/usage.rst
> github: check rst syntax

- docs/source/deployment.rst
- docs/source/html/asciinema-tf-clean.html
> docs: add asciinema tf-clean

- terraform/environment-ovh.tfvars
- terraform/manager.tf
- terraform/neutron.tf
- terraform/nodes.tf
- terraform/variables.tf
> terraform: add port_security_enabled variable

- .github/workflows/ansible-inventory.yml
> github: add 'Verify ansible inventory' workflow

- docs/source/usage.rst
- environments/custom/playbook-bootstrap-patchman.yml
- scripts/deploy_infrastructure_services.sh
> custom: add playbook to bootstrap patchman

- docs/source/usage.rst
- scripts/deploy_infrastructure_services_basic.sh
- scripts/deploy_infrastructure_services_extented.sh
- terraform/manager.tf
> Split deploy_infrastructure_services.sh script

- docs/requirements.txt
- requirements.txt
> Pin python requirements

- .github/pr-labeler.yml
> github: add renovate to PR labeler config

- terraform/files/manager-part-2.yml
> Install kata containers on the manager node (pt. 2)

- docs/source/conf.py
> docs: use app.add_css_file()

- terraform/nodes.tf
> terraform: make number of volumes configurable

- terraform/files/cleanup.sh
- terraform/files/cleanup.yml
> terraform: improve python2 cleanup

- terraform/files/cleanup.yml
> terraform: add missing become

- environments/configuration.yml
> Remove security_rhel7_automatic_package_updates parameter

- inventory/hosts
> inventory: add pulp host group

- environments/custom/playbook-bootstrap-patchman.yml
> custom: remove bootstrap-patchman playbook

- inventory/hosts
> inventory: add netbox host group

- environments/configuration.yml
- environments/generic/configuration.yml
- inventory/hosts
- scripts/deploy_monitoring_services.sh
> Deploy zabbix-agent

- terraform/Makefile
> terraform: add openstack command to Makefile (pt. 2)

- environments/configuration.yml
> Enable sysdig repository

- environments/infrastructure/configuration.yml
- environments/monitoring/configuration.yml
- environments/monitoring/images.yml
- environments/monitoring/secrets.yml
> Add monitoring environment

- docs/source/usage.rst
- scripts/deploy_monitoring_services.sh
> Use osism-monitoring for monitoring services

- environments/configuration.yml
- environments/manager/images.yml
> Add docker_registry_ansible parameter

- terraform/files/manager-part-3.yml
> Set docker_registry_ansible in manager-part-3 playbook

- inventory/hosts
> inventory: add common host groups

- environments/manager/configuration.yml
> manager: enable vault service

- environments/ceph/configuration.yml
- environments/configuration.yml
> Use 00000000-0000-0000-0000-000000000000 as ceph fsid

- inventory/hosts
> inventory: add zabbix host group

- docs/source/usage.rst
- environments/infrastructure/configuration.yml
> Move phpmyadmin to the management network

- inventory/00-global
> inventory: disable testbed-node-2 in 00-global

- inventory/50-infrastruture
> inventory: add ucs host group

- environments/manager/configuration.yml
> manager: deploy netbox service

- .github/renovate.json
> renovate: add commitBody

- environments/configuration.yml
> Enable falco repository

- inventory/00-global
- inventory/20-roles
> inventory: add generic role

- inventory/20-roles
> inventory: fix generic host group

- docs/source/usage.rst
> docs: fix netbox figure

- inventory/host_vars/testbed-manager.osism.local.yml
- inventory/host_vars/testbed-node-0.osism.local.yml
- inventory/host_vars/testbed-node-1.osism.local.yml
- inventory/host_vars/testbed-node-2.osism.local.yml
> inventory: add netbox inventory status

- environments/configuration.yml
> Remove repository parameters

- inventory/20-roles
> inventory: sync 20-roles

- environments/configuration.yml
- terraform/manager.tf
> Fix operator_authorized_keys

- environments/configuration.yml
> Remove hardening parameters

- environments/infrastructure/configuration.yml
> Remove infrastructure parameters

- .github/workflows/terraform.yml
- terraform/main.tf
> github: test terraform 0.12.29 & 0.13.0

- environments/custom/playbook-wireguard.yml
> Set apt_repository mode = 0600

- scripts/deploy_infrastructure_services_extented.sh
> Use 'osism-infrastructure phpmyadmin' to deploy phpmyadmin

- scripts/deploy_helper_services.sh
> Use 'osism-manager sshconfig' to deploy sshconfig

- environments/configuration.yml
> Disable networkd services

- terraform/files/manager-part-1.yml
- terraform/files/manager-part-2.yml
- terraform/files/manager-part-3.yml
- terraform/files/node.yml
> Install docker-compose from repository

- environments/openstack/playbook-bootstrap-octavia.yml
- environments/openstack/playbook-bootstrap-refstack.yml
> Fix 'File permissions not mentioned' ansible-lint issue

- environments/configuration.yml
- environments/kolla/files/overlays/zun/zun-compute.conf
- terraform/files/manager-part-2.yml
> Disable kata containers

- terraform/manager.tf
> Fix wrong host group

- terraform/nodes.tf
> terraform: node resources require a router

- terraform/neutron.tf
> terraform: name the router

- environments/ansible.cfg
> Remove inventory from ansible configuration

- environments/manager/configuration.yml
> manager: temporary deactivation of netbox

- terraform/environment-betacloud.tfvars
> Use the Ubuntu 18.04 image on the Betacloud

- .github/workflows/terraform.yml
> github: test terraform 0.13.2

- environments/configuration.yml
- terraform/files/manager-part-1.yml
- terraform/files/manager-part-2.yml
- terraform/files/node.sh
- terraform/files/node.yml
- terraform/manager.tf
> terraform: use ansible collections

- environments/openstack/playbook-bootstrap-basic.yml
> openstack: add key to test instance

- terraform/files/node.sh
> Set APT::Acquire::Retries = 3 as default

- environments/configuration.yml
- terraform/files/manager-part-2.yml
- terraform/files/node.yml
> Use docker version 19.03.12

- .github/workflows/terraform.yml
> github: test terraform 0.13.3

- terraform/neutron.tf
> terraform: improve network names

- terraform/manager.tf
> terraform: add manager_floating_ip_association resource

- terraform/Makefile
> terraform: add support to import an existing floating ip address

- terraform/Makefile
> terraform: improve initialization

- terraform/Makefile
> terraform: use StrictHostKeyChecking=no

- terraform/Makefile
> terraform: add create/log/login aliases to the makefile

- terraform/Makefile
> terraform: add command to print a table with all endpoints

- terraform/neutron.tf
> terraform: allow access on tcp ports 8110/8120/8130

- .github/workflows/deploy-daily-citycloud.yml
> github: run daily deployment (citycloud)

- environments/custom/playbook-fetch-ceph-keys.yml
- environments/openstack/playbook-bootstrap-basic.yml
- environments/openstack/playbook-bootstrap-magnum.yml
- environments/openstack/playbook-bootstrap-octavia.yml
- environments/openstack/playbook-bootstrap-refstack.yml
> Fix "too few spaces before comment" syntax issue in yaml files

- terraform/Makefile
> terraform: rename SSH_USERNAME to USERNAME

- .github/workflows/deploy-daily-citycloud.yml
- .github/yamllint.yml
- contrib/rally/rally.conf
- contrib/rally/rally.json
- contrib/rally/rally.sh
- contrib/rally/tests/README.rst
- contrib/rally/tests/macro/macro.yml
- contrib/rally/tests/scenario/authentication.yml
- contrib/rally/tests/scenario/cinder.yml
- contrib/rally/tests/scenario/glance.yml
- contrib/rally/tests/scenario/keystone.yml
- contrib/rally/tests/scenario/neutron.yml
- contrib/rally/tests/scenario/nova.yml
- contrib/rally/tests/scenario/quota.yml
- contrib/rally/tests/task-arguments.yml
- contrib/rally/tests/task.yml
- docs/source/usage.rst
- environments/openstack/playbook-bootstrap-basic.yml
- terraform/manager.tf
- terraform/variables.tf
> contrib: add rally

- .gitignore
- terraform/Makefile
> terraform: add command to push a state

- environments/openstack/playbook-bootstrap-basic.yml
> openstack: add ubuntu minimal 20.04 image

- docs/source/deployment.rst
- environments/infrastructure/configuration.yml
- environments/kolla/configuration.yml
- environments/manager/configuration.yml
- environments/manager/images.yml
- environments/openstack/playbook-bootstrap-basic.yml
- scripts/set-openstack-version.sh
- terraform/variables.tf
> Use openstack ussuri

- docs/source/overview.rst
- environments/kolla/files/overlays/neutron.conf
- environments/openstack/playbook-bootstrap-basic.yml
> neutron: reduce mtu to 1300

- environments/openstack/playbook-bootstrap-basic.yml
> Add medium flavor

- environments/kolla/configuration.yml
- environments/kolla/files/overlays/nova/nova-compute.conf
> Use kvm by default

- terraform/manager.tf
> manager: install the ansible.netcommon collection

- terraform/Makefile
> terraform: add tunnel alias to Makefile

- environments/openstack/playbook-bootstrap-octavia-pre.yml
> openstack: fix the bootstrap-octavia-pre playbook

- .github/yamllint.yml
- environments/custom/playbook-bootstrap-ceph-dashboard.yml
- environments/custom/playbook-bootstrap-patchman.yml
- environments/custom/playbook-fetch-ceph-keys.yml
- environments/custom/playbook-generate-ssh-known-hosts.yml
- environments/custom/playbook-wireguard.yml
> github: enable yamllint check 'comments'

- environments/openstack/playbook-bootstrap-octavia-pre.yml
- inventory/host_vars/testbed-node-0.osism.test.yml
- inventory/host_vars/testbed-node-1.osism.test.yml
- inventory/host_vars/testbed-node-2.osism.test.yml
> octavia: fix used mtu

- .github/workflows/deploy-daily-citycloud.yml
- .github/workflows/validate-terraform.yml
> github: use terraform 0.13.5

- terraform/main.tf
> terraform: require version 0.13

- inventory/host_vars/testbed-manager.osism.test.yml
- inventory/host_vars/testbed-node-0.osism.test.yml
- inventory/host_vars/testbed-node-1.osism.test.yml
- inventory/host_vars/testbed-node-2.osism.test.yml
- terraform/files/node.sh
> inventory: calculate node IP addresses

- .github/workflows/deploy-daily-citycloud.yml
> github: only re-deploy on a push on master

- .github/workflows/deploy-daily-citycloud.yml
> github: fix wrong terraform version

- environments/openstack/playbook-bootstrap-refstack.yml
> Improve the bootstrap playbook for refstack

- docs/LICENSE
> docs: add LICENSE file

- terraform/files/node.sh
> Fix focal default route

- terraform/Makefile
> terraform: add new Makefile comand "console" to get the console url

- terraform/scripts/cleanup.py
> terraform: add a helper script that can cleanup a stucked project

- terraform/files/node.sh
- terraform/manager.tf
- terraform/nodes.tf
> Some more fixes required by focal

- docs/source/deployment.rst
> docs: extend the usage section

- docs/source/deployment.rst
> docs: shuttle -> sshuttle

- environments/configuration.yml
- terraform/files/manager-part-2.yml
- terraform/files/node.yml
> Use docker version 19.03.13

- environments/openstack/playbook-bootstrap-octavia-pre.yml
> Fix wrong octavia image

- README.md
> README: testbed was _initially_ created by

- environments/kolla/configuration.yml
> kolla: use rolling images

- terraform/files/node.sh
> Use ansible >= 2.10

- terraform/files/node.sh
> Fix installations via ansible-galaxy

- environments/ceph/configuration.yml
- environments/configuration.yml
> ceph: use quay images

- inventory/host_vars/testbed-node-0.osism.test.yml
- inventory/host_vars/testbed-node-1.osism.test.yml
- inventory/host_vars/testbed-node-2.osism.test.yml
> Remove node_id parameter

- .github/workflows/build-documentation.yml
- .github/workflows/check-ansible-inventory.yml
- .github/workflows/check-ansible-syntax.yml
- .github/workflows/check-python-syntax.yml
- .github/workflows/check-rst-syntax.yml
- .github/workflows/check-terraform-syntax.yml
- .github/workflows/check-yaml-syntax.yml
- .github/workflows/deploy-daily-citycloud.yml
- .github/workflows/pr-labeler.yml
> github: rename workflows

- .github/workflows/build-documentation.yml
> github: use SamKirkland/FTP-Deploy-Action

- README.md
> README: remove author information

- scripts/002-infrastructure-services-basic.sh
- scripts/004-openstack-services-basic.sh
> Add --skip-tags to deployment scripts

- environments/ansible.cfg
> Enable Ansible profiling

- environments/configuration.yml
> Cleanup osism-serial values

- environments/ansible.cfg
> Only profile Ansible tasks

- docs/source/deployment.rst
> docs: fix syntax issue

- terraform/manager.tf
> 001-helper_services.sh -> 001-helper-services.sh

- requirements.txt
> Remove unused requirements.txt file

- .github/workflows/daily-citycloud.yml
> github: rename daily citycloud workflow & jobs

- .github/workflows/daily-citycloud.yml
> github: add openstack-version parameter to daily-citycloud

- .github/workflows/daily-citycloud.yml
> github: fix wrong filename & requirement in daily-citycloud

- .github/workflows/daily-citycloud.yml
> github: use victoria for daily deployment

- docs/source/deployment.rst
- docs/source/overview.rst
- environments/custom/images.yml
- environments/infrastructure/configuration.yml
- environments/kolla/configuration.yml
- environments/kolla/images.yml
- environments/manager/configuration.yml
- environments/manager/images.yml
- environments/openstack/playbook-bootstrap-octavia-pre.yml
- scripts/set-openstack-version.sh
- terraform/variables.tf
> Use openstack victoria

- environments/manager/configuration.yml
> Fix the manager_version parameter

- environments/manager/images.yml
> docker_postgres -> docker_registry

- terraform/manager.tf
> terraform: remove redundance from the manager.sh script

- environments/openstack/clouds.yml
- environments/openstack/playbook-bootstrap-basic.yml
- environments/openstack/secure.yml
> Add openstack-health-monitor configuration

- environments/openstack/playbook-bootstrap-basic.yml
> openstack: make ubuntu 20.04 image visible

- environments/openstack/playbook-bootstrap-basic.yml
> openstack: set min_disk size

- .github/workflows/check-terraform-syntax.yml
- .github/workflows/daily-citycloud.yml
- terraform/main.tf
> Use terraform 0.14

- terraform/main.tf
> terraform: use terraform-provider-openstack/openstack

- environments/configuration.yml
- terraform/files/manager-part-2.yml
- terraform/files/node.yml
> docker: use docker 20.10.0

- environments/manager/images.yml
> Remove aptly & installer images

- environments/configuration.yml
- environments/manager/images.yml
> Add docker_registry_service

- environments/manager/images.yml
> manager: fix registry variables

- environments/configuration.yml
> Fix docker_registry_service

- terraform/files/node.yml
> Cleanup node.yml playbook

- environments/manager/images.yml
> Use docker_registry_cephclient + docker_registry_openstackclient

- environments/manager/images.yml
> manager: add awxclient image

- environments/configuration.yml
> Remove resolvconf_package variable

- inventory/host_vars/testbed-manager.osism.test.yml
- inventory/host_vars/testbed-node-0.osism.test.yml
- inventory/host_vars/testbed-node-1.osism.test.yml
- inventory/host_vars/testbed-node-2.osism.test.yml
> Remove network variables no longer required

- environments/configuration.yml
> Use docker overlay2 by default

- environments/kolla/configuration.yml
> kolla: remove defaults

- environments/kolla/configuration.yml
> kolla: remove defaults (pt. 2)

- inventory/99-overwrite
> inventory: add cephclient overwrite group

- inventory/10-custom
- inventory/20-roles
- inventory/99-overwrite
> inventory: rename testbed-manager group

- scripts/001-helper-services.sh
> Fix sshconfig environment in 001-helper-services.sh

- inventory/99-overwrite
> inventory: fix wrong hostname

- environments/custom/playbook-generate-ssh-known-hosts.yml
> Fix generate-ssh-known-hosts

- environments/manager/configuration.yml
> manager: use sqlite

- README.md
- docs/source/index.rst
> Remove "Hyperconverged infrastructure (HCI)"

- .github/workflows/daily-citycloud.yml
- terraform/Makefile
> terraform: add deploy-full target to Makefile

- terraform/manager.tf
> terraform: fix reboot of nodes

- scripts/004-openstack-services-basic.sh
> Deploy barbican service

- inventory/host_vars/testbed-manager.osism.test.yml
- inventory/host_vars/testbed-node-0.osism.test.yml
- inventory/host_vars/testbed-node-1.osism.test.yml
- inventory/host_vars/testbed-node-2.osism.test.yml
> inventory: remove ansibl.netcommon prefix

- inventory/99-overwrite
> inventory: add missing ceph groups

- inventory/99-overwrite
> inventory: deploy the cephclient on the manager only

- terraform/Makefile
> terraform: add ping target

- terraform/neutron.tf
- terraform/variables.tf
> terraform: add dns_nameservers variable

- environments/ceph/configuration.yml
> ceph: set osds_per_device = 2

- environments/configuration.yml
> Run docker role on all nodes at once

- terraform/files/node.sh
> terraform: remove pre-intalled ansible

- terraform/Makefile
> terraform: make terraform binary configurable

- docs/source/deployment.rst
- scripts/999-identity-services.sh
- terraform/Makefile
- terraform/manager.tf
- terraform/variables.tf
> Add a target to build an identity testbed

- docs/source/deployment.rst
> docs: install terraform

- environments/kolla/configuration.yml
Co-authored-by: Tim Beermann <beermann@betacloud-solutions.de>
> kolla: reduce the number of service workers

- environments/configuration.yml
- terraform/files/manager-part-2.yml
- terraform/files/node.yml
> Use docker version 20.10.5

- environments/configuration.yml
- inventory/host_vars/testbed-manager.osism.test.yml
- inventory/host_vars/testbed-node-0.osism.test.yml
- inventory/host_vars/testbed-node-1.osism.test.yml
- inventory/host_vars/testbed-node-2.osism.test.yml
> Make testbed mtu configurable

- docs/source/index.rst
> docs: link the ix article

- terraform/files/node.sh
> terraform: use ansible 3

- terraform/Makefile
> terraform: add graph target

- scripts/004-openstack-services-basic.sh
> Deploy the openstack-health-monitor by default

- inventory/99-overwrite
> inventory: add note to 99-overwrite

- environments/openstack/playbook-bootstrap-basic.yml
> openstack: fix wrong hot group in the bootstrap-basic playbook

- environments/custom/playbook-bootstrap-ceph-dashboard.yml
> Restart the ceph dashboard after required config changes

- environments/custom/playbook-bootstrap-ceph-dashboard.yml
> Fix the creation of the ceph dashboard admin user

- .github/workflows/check-terraform-syntax.yml
> github: use terraform 0.14.9

- environments/kolla/configuration.yml
The ``neutron-fwaas`` project is no longer maintained.
> kolla: remove fwaas parameters

- terraform/manager.tf
- terraform/nodes.tf
- terraform/variables.tf
> terraform: add enable_config_drive variable

- environments/kolla/files/overlays/haproxy/services.d/haproxy.cfg
Co-authored-by: Uwe Grawert <grawert@b1-systems.de>
> kolla: sync swift haproxy configuration with upstream

- docs/source/index.rst
> docs: mention OTC in the idnex file

- environments/kolla/files/overlays/haproxy/services.d/haproxy.cfg
> kolla: add missing l to haproxy configuration

- contrib/check_infrastructure_services.sh
- docs/source/deployment.rst
- docs/source/networking.rst
- docs/source/usage.rst
- environments/configuration.yml
- environments/custom/files/wireguard/client.conf
- environments/custom/playbook-wireguard.yml
- environments/kolla/files/overlays/cinder/ceph.conf
- environments/kolla/files/overlays/glance/ceph.conf
- environments/kolla/files/overlays/gnocchi/ceph.conf
- environments/kolla/files/overlays/nova/ceph.conf
- inventory/host_vars/testbed-manager.osism.test.yml
- inventory/host_vars/testbed-node-0.osism.test.yml
- inventory/host_vars/testbed-node-1.osism.test.yml
- inventory/host_vars/testbed-node-2.osism.test.yml
- terraform/Makefile
- terraform/files/node.sh
- terraform/manager.tf
- terraform/neutron.tf
- terraform/nodes.tf
- terraform/overrides/neutron_availability_zone_hints_override.tf
> Reduce overall number of virtual networks

- terraform/Makefile
> terraform: add plan target to the Makefile

- terraform/Makefile
> terraform: make parallelism configurable

- terraform/Makefile
> terraform: make parallelism configurable (pt. 2)

- terraform/scripts/cleanup.py
> Make cleanup of volumes possible on the OTC as well

- .gitignore
- docs/source/deployment.rst
- terraform/data.tf
- terraform/environments/betacloud.tfvars
- terraform/environments/citycloud.tfvars
- terraform/environments/local.tfvars.sample
- terraform/environments/otc.tfvars
- terraform/environments/otcbms.tfvars
- terraform/environments/ovh.tfvars
- terraform/environments/pluscloudopen.tfvars
- terraform/environments/scs-demo.tfvars
- terraform/files/node.sh
- terraform/manager.tf
- terraform/neutron.tf
- terraform/nodes.tf
- terraform/overrides/manager_boot_from_image_override.tf
- terraform/overrides/manager_boot_from_volume_override.tf
- terraform/overrides/manager_port_fixed_ip_address_override.tf
- terraform/overrides/nodes_boot_from_image_override.tf
- terraform/overrides/nodes_boot_from_volume_override.tf
- terraform/overrides/nodes_port_fixed_ip_address_override.tf
- terraform/terragrunt.hcl
- terraform/variables.tf
Closes #499
Co-authored-by: Tim Beermann <beermann@betacloud-solutions.de>
> Support bare-metal OTC deployment (pt. 1)

- inventory/host_vars/testbed-manager.osism.test.yml
> inventory: use virtual nics on the manager

- terraform/manager.tf
> terraform: add network devices on the manager without a reboot

- terraform/Makefile
> terraform: add a push target to the Makefile

- inventory/host_vars/testbed-manager.osism.test.yml
- inventory/host_vars/testbed-node-0.osism.test.yml
- inventory/host_vars/testbed-node-1.osism.test.yml
- inventory/host_vars/testbed-node-2.osism.test.yml
- terraform/environments/betacloud.tfvars
- terraform/environments/citycloud.tfvars
- terraform/environments/ovh.tfvars
- terraform/environments/pluscloudopen.tfvars
- terraform/environments/scs-demo.tfvars
- terraform/manager.tf
- terraform/neutron.tf
- terraform/nodes.tf
- terraform/overrides/manager_port_fixed_ip_address_override.tf
- terraform/overrides/neutron_availability_zone_hints_override.tf
- terraform/overrides/nodes_port_fixed_ip_address_override.tf
> Use internal vxlan as provider network

- environments/custom/playbook-generate-ssh-known-hosts.yml
> custom: fix yamllint warning

- inventory/host_vars/testbed-manager.osism.test.yml
- inventory/host_vars/testbed-node-0.osism.test.yml
- inventory/host_vars/testbed-node-1.osism.test.yml
- inventory/host_vars/testbed-node-2.osism.test.yml
> inventory: fix network up/down scripts

- environments/custom/playbook-workarounds.yml
- environments/custom/templates/workarounds.service.j2
- environments/custom/templates/workarounds.sh.j2
- terraform/manager.tf
> custom: add a workarounds playbook

- terraform/Makefile
> terraform: add a reset target to the Makefile

- .github/workflows/check-terraform-syntax.yml
- .gitignore
- terraform/Makefile
- terraform/customisations/default_custom.tf
- terraform/customisations/otcbms_custom.tf
- terraform/data.tf
- terraform/environments/betacloud.tfvars
- terraform/environments/citycloud.tfvars
- terraform/environments/default.tfvars
- terraform/environments/otc.tfvars
- terraform/environments/otcbms.tfvars
- terraform/environments/ovh.tfvars
- terraform/environments/pluscloudopen.tfvars
- terraform/environments/scs-demo.tfvars
- terraform/main.tf
- terraform/manager.tf
- terraform/nodes.tf
- terraform/overrides/nodes_boot_from_image_override.tf
- terraform/overrides/nodes_boot_from_volume_otcbms_override.tf
- terraform/variables.tf
Partial #499
Co-authored-by: Tim Beermann <beermann@betacloud-solutions.de>
> Support bare-metal OTC deployment (pt. 2)

- terraform/scripts/cleanup.py
> terraform: remove floating IPs last

- docs/source/deployment.rst
- docs/source/overview.rst
- docs/source/usage.rst
- environments/ceph/configuration.yml
- environments/infrastructure/configuration.yml
- environments/manager/configuration.yml
- scripts/set-ceph-version.sh
- terraform/variables.tf
> Use ceph octopus

- environments/manager/configuration.yml
> manager: remove netbox_enable parameter

- environments/manager/images.yml
> manager: use awxclient 19.0.0

- environments/manager/configuration.yml
- environments/manager/images.yml
> manager: use awx_version

- .github/workflows/check-terraform-syntax.yml
- .github/workflows/daily-citycloud.yml
> github: use terraform 0.15.0

- environments/manager/images.yml
> manager: use ara 1.5.6

- docs/source/overview.rst
- environments/kolla/configuration.yml
- scripts/007-openstack-services-extented.sh
> kolla: enable senlin service

- environments/configuration.yml
- terraform/files/manager-part-2.yml
- terraform/files/node.yml
> Use docker version 20.10.6

- terraform/files/node.yml
> Add a 3rd part to the node bootstrap playbook

- inventory/host_vars/testbed-manager.osism.test.yml
- network/iptables.sh
- network/vxlan.sh
> Use netplan for the network configuration of the manager

- inventory/host_vars/testbed-node-0.osism.test.yml
- inventory/host_vars/testbed-node-1.osism.test.yml
- inventory/host_vars/testbed-node-2.osism.test.yml
> Use netplan for the network configuration of the nodes

- inventory/host_vars/testbed-manager.osism.test.yml
- inventory/host_vars/testbed-node-0.osism.test.yml
- inventory/host_vars/testbed-node-1.osism.test.yml
- inventory/host_vars/testbed-node-2.osism.test.yml
- network/vxlan.sh
> inventory: use node_id parameter

- environments/custom/playbook-bootstrap-ceph-dashboard.yml
> custom: fix bootstrap-ceph-dashboard playbook

- inventory/host_vars/testbed-manager.osism.test.yml
> Avoid docker restart on the manger node

- .github/workflows/update-manager-images.yml
> github: add "Update manager images"  workflow

- terraform/files/manager-part-3.yml
> manager: deploy netbox by default

- environments/manager/configuration.yml
- environments/manager/secrets.yml
> manager: enable netbox integration

- docs/source/usage.rst
- environments/secrets.yml
> Use password as password for ARA & patchman

- terraform/Makefile
> terraform: add a copy target to the Makefile

- terraform/Makefile
> terraform: add a address target to the Makefile

- environments/kolla/configuration.yml
> kolla: do not become by default

- .github/workflows/check-terraform-syntax.yml
> github: fix "Check terraform syntax" workflow

- README.md
> README: add github actions

- environments/ceph/configuration.yml
> ceph: set mon auth_allow_insecure_global_id_reclaim false

- docs/source/deployment.rst
-https://gx-scs.okeanos.dev/
+https://ui.gx-scs.sovereignit.cloud/
Signed-off-by: Mathias Fechner <mathias.fechner@plusserver.com>
> Switch SCS-Demonstrator URL:

- environments/infrastructure/configuration.yml
> infrastructure: add jenkins host

- environments/custom/playbook-facts.yml
- environments/custom/playbook-wireguard.yml
> Use apt task

- environments/ansible.cfg
> Set ssh_args parameter in Ansible configuration

- contrib/check_infrastructure_services.sh
- contrib/check_openstack_services.sh
- terraform/Makefile
> terraform: add a check target to the Makefile

- contrib/check_infrastructure_services.sh
> contrib: add ceph to check_infrastructure_services.sh

- contrib/rally/rally.sh
- contrib/rally/tests/scenario/neutron.yml
- terraform/Makefile
> terraform: add a rally target to the Makefile

- environments/configuration.yml
- inventory/host_vars/testbed-manager.osism.test.yml
- inventory/host_vars/testbed-node-0.osism.test.yml
- inventory/host_vars/testbed-node-1.osism.test.yml
- inventory/host_vars/testbed-node-2.osism.test.yml
> Allow different MTU sizes for managers and nodes

- environments/custom/playbook-workarounds.yml
- inventory/host_vars/testbed-node-0.osism.test.yml
- inventory/host_vars/testbed-node-1.osism.test.yml
- inventory/host_vars/testbed-node-2.osism.test.yml
> Repair the network configuration on OTC BMS nodes

- environments/custom/playbook-workarounds.yml
> Repair the network configuration on OTC BMS nodes (pt. 2)

- environments/custom/templates/workarounds.sh.j2
> Fix the workaround script for netplan

- environments/custom/files/testbed_network_devices.fact
> Ignore genev interfaces in testbed_network_devices.fact

- docs/source/usage.rst
- environments/custom/configuration.yml
- environments/custom/playbook-wireguard.yml
- environments/custom/templates/wireguard/client.conf.j2
- environments/custom/templates/wireguard/server.conf.j2
> custom: improve wireguard configuration

- environments/generic/configuration.yml
> Fix patchman_client_host & zabbix_agent_server

- environments/monitoring/configuration.yml
> Fix arguments used in the monitoring environment

- inventory/20-roles
- terraform/customisations/otcbms_custom.tf
- terraform/environments/otcbms.tfvars
- terraform/overrides/nodes_boot_from_image_otcbms_override.tf
- terraform/variables.tf
> Improve the OTC BMS environment

- .ansible-lint
- environments/custom/playbook-bootstrap-ceph-dashboard.yml
> Add ansible-lint configuration file

- scripts/002-infrastructure-services-basic.sh
> Add keycloak deployment to 002-infrastructure-services-basic.sh

- environments/kolla/configuration.yml
> kolla: fix neutron-plugin-agent for wallaby

- environments/custom/playbook-workarounds-ceph.yml
- environments/custom/playbook-workarounds.yml
- scripts/003-ceph-services.sh
- terraform/manager.tf
> Move ceph workarounds into a dedicated playbook

- environments/kolla/configuration.yml
> kolla: do not enable sanity checks by default

- contrib/refstack/refstack.sh
- terraform/Makefile
> refstack: use guideline 2020.11

- environments/configuration.yml
> resolvconf: disable dnssec

- terraform/files/node.yml
> terraform: add missing resolvconf parameters

- environments/custom/playbook-workarounds.yml
> Apply netplan configuration on all nodes

- docs/source/notes.rst
related https://github.com/osism/testbed/issues/761#issuecomment-871395996
> There was a word missing. I assumed that *create* fits quite well.

- docs/source/deployment.rst
related https://github.com/osism/testbed/issues/761
> Made *make watch* more understandable

- docs/source/deployment.rst
> docs: rename 'Supported cloud providers'

- docs/source/deployment.rst
> docs: add urls to csp signup formulars

- docs/source/deployment.rst
> docs: beta cloud -> Betacloud

- docs/source/deployment.rst
related https://github.com/osism/testbed/issues/761
> added and restructured some text to avoid confusion

- README.md
- docs/source/conf.py
- docs/source/notes.rst
> Use docs.osism.tech

- .github/workflows/check-terraform-syntax.yml
- .github/workflows/daily-citycloud.yml
- terraform/main.tf
> Use terraform >= 1.0.0

- environments/custom/files/testbed_ceph_devices.fact
- environments/custom/files/testbed_ceph_devices_all.fact
> custom: use readlink to resolve /dev/root

- environments/configuration.yml
- terraform/files/node.yml
> Do not apply the systohc role

- environments/custom/files/testbed_ceph_devices.fact
- environments/custom/files/testbed_ceph_devices_all.fact
- environments/custom/playbook-facts.yml
> custom: use a better approach to more reliably determine the Ceph block devices

- .github/workflows/daily-citycloud.yml
> github: add workflow_dispatch to "Daily citycloud" workflow

- .github/workflows/daily-citycloud.yml
- terraform/Makefile
> github: add missing arguments to the "Daily citycloud" workflow

- .github/workflows/update-manager-images.yml
> github: rename OSISM bot

- docs/source/contributing.rst
- docs/source/index.rst
> docs: add how to contribute section

- .github/workflows/longterm-otcbms.yml
- README.md
> github: add "Longterm OTCBMS" workflow

- terraform/customisations/default_custom.tf
- terraform/customisations/otcbms_custom.tf
- terraform/manager.tf
> terraform: update packages

- terraform/files/manager.sh
- terraform/manager.tf
> terraform: reduce manager.sh template

- .github/workflows/daily-citycloud.yml
- docs/source/deployment.rst
- docs/source/overview.rst
- environments/infrastructure/configuration.yml
- environments/kolla/configuration.yml
- environments/manager/configuration.yml
- environments/manager/images.yml
- environments/openstack/playbook-bootstrap-basic.yml
- inventory/host_vars/testbed-node-0.osism.test.yml
- inventory/host_vars/testbed-node-1.osism.test.yml
- inventory/host_vars/testbed-node-2.osism.test.yml
- inventory/host_vars/testbed-node-3.osism.test.yml
- inventory/host_vars/testbed-node-4.osism.test.yml
- inventory/host_vars/testbed-node-5.osism.test.yml
- inventory/host_vars/testbed-node-6.osism.test.yml
- inventory/host_vars/testbed-node-7.osism.test.yml
- inventory/host_vars/testbed-node-8.osism.test.yml
- inventory/host_vars/testbed-node-9.osism.test.yml
- scripts/set-openstack-version.sh
- terraform/variables.tf
> Use openstack wallaby release as default

- environments/manager/images.yml
> manager: add client versions

- docs/source/conf.py
- docs/source/deployment.rst
- environments/configuration.yml
- terraform/Makefile
- terraform/variables.tf
> master -> main

- docs/source/deployment.rst
- docs/source/index.rst
> docs: remove some quotes

- docs/source/deployment.rst
- environments/ceph/configuration.yml
- environments/infrastructure/configuration.yml
- environments/manager/configuration.yml
- environments/manager/images.yml
- scripts/set-ceph-version.sh
- terraform/Makefile
- terraform/variables.tf
> Use pacific as ceph default version

- .github/workflows/build-documentation.yml
- .github/workflows/daily-citycloud.yml
- .github/workflows/longterm-otcbms.yml
> Improve github workflows a little bit

- environments/ceph/configuration.yml
- environments/configuration.yml
- environments/infrastructure/configuration.yml
- environments/kolla/configuration.yml
> Cleanup versions

- scripts/set-ceph-version.sh
- scripts/set-manager-version.sh
- scripts/set-openstack-version.sh
- terraform/Makefile
- terraform/files/manager.sh
- terraform/manager.tf
- terraform/variables.tf
> terraform: set manager version

- environments/kolla/configuration.yml
> kolla: use ovn as default neutron_plugin_agent

- environments/openstack/playbook-bootstrap-basic.yml
> Add tiny SCS flavors

- docs/source/usage.rst
> docs: add updates & upgrades

- environments/openstack/playbook-bootstrap-basic.yml
> openstack: set SCS image meta data for Ubuntu 20.04 image

- docs/source/overview.rst
> docs: use sbom

- environments/openstack/playbook-bootstrap-basic.yml
> openstack: add more scs flavors

- docs/source/contributing.rst
- docs/source/index.rst
- docs/source/overview.rst
> docs: extend index

- docs/source/overview.rst
> docs: add links to kolla-ansible + ceph-ansible

- environments/custom/playbook-keycloak-ldap-federation-config.yml
> custom: improve keycloak-ldap-federation-config

- environments/custom/configuration.yml
- environments/custom/playbook-keycloak-ldap-federation-config.yml
- environments/custom/playbook-keycloak-oidc-client-config.yml
- environments/custom/secrets.yml
> custom: improve keycloak playbooks

- environments/manager/images.yml
> chore: update versions in environments/manager/images.yml

- environments/kolla/configuration.yml
> kolla: add nova_libvirt_extra_volumes

- contrib/rally/tests/task-arguments.yml
- contrib/rally/tests/task.yml
- environments/openstack/playbook-bootstrap-basic.yml
> Remove non-SCS flavors

- environments/openstack/playbook-bootstrap-basic.yml
> openstack: move SCS flavors near the top

- docs/source/usage.rst
> docs: OIDC Authentication

- docs/source/usage.rst
> docs: document limitations around Keycloak OIDC without SSL

- terraform/Makefile
- terraform/integration-tests/docker-compose.yaml
- terraform/integration-tests/run_test.sh
- terraform/integration-tests/tests/new_user.robot
> test(keycloak): Test login to Horizon via Keycloak LDAP federation

- environments/custom/configuration.yml
- environments/custom/files/openldap/domain-admin-policy.ldif.j2
- environments/custom/files/openldap/umc-policies.ldif.j2
- environments/custom/playbook-keycloak-ldap-federation-config.yml
- environments/custom/playbook-openldap-umc-policies.yml
- environments/custom/playbook-umc-admin-ldap.yml
- environments/custom/secrets.yml
- scripts/999-identity-services.sh
> custom: use a separate umc-admin LDAP user with admin privileges

- environments/kolla/configuration.yml
> kolla: enable prometheus server

- scripts/009-baremetal-services.sh
> Add script to deploy virtualbmc

- .gitignore
- environments/kolla/configuration.yml
- scripts/009-baremetal-services.sh
- scripts/009-openstack-services-baremetal.sh
- terraform/files/manager.sh
> Deploy ironic with 009-openstack-services-baremetal.sh

- docs/source/overview.rst
> docs: add ironic & remove magnum

- docs/source/usage.rst
> docs: document token lifespans around Keycloak OIDC

- .github/workflows/check-terraform-syntax.yml
- .github/workflows/daily-citycloud.yml
- .github/workflows/longterm-otcbms.yml
> github: use terraform 1.0.7 and only run longterm-otcbms on request

- contrib/refstack/refstack.sh
> contrib: fix refstack

- contrib/refstack/accounts.yaml
- contrib/refstack/run.sh
- contrib/refstack/single.sh
- contrib/refstack/tempest.conf
- contrib/refstack/upload.sh
- docs/source/usage.rst
- environments/openstack/playbook-bootstrap-refstack.yml
- terraform/Makefile
- terraform/files/manager.sh
> refstack: add upload helper script

- contrib/refstack/tempest.conf
> refstack: fix some swift tests

- contrib/rally/tests/task-arguments.yml
- contrib/rally/tests/task.yml
- environments/openstack/playbook-bootstrap-basic.yml
- environments/openstack/playbook-bootstrap-refstack.yml
> Use cirros 0.5.2

- docs/source/usage.rst
> Webinterface links are opened in a new tab now

- scripts/006-infrastructure-services-extented.sh
> Remove call of the osquery playbook

- docs/source/usage.rst
> netbox: change netbox user to admin

- .github/workflows/build-documentation.yml
- .github/workflows/update-manager-images.yml
> github: disable some workflows/actions on forks

- inventory/host_vars/testbed-manager.osism.test.yml
- inventory/host_vars/testbed-node-0.osism.test.yml
- inventory/host_vars/testbed-node-1.osism.test.yml
- inventory/host_vars/testbed-node-2.osism.test.yml
- inventory/host_vars/testbed-node-3.osism.test.yml
- inventory/host_vars/testbed-node-4.osism.test.yml
- inventory/host_vars/testbed-node-5.osism.test.yml
- inventory/host_vars/testbed-node-6.osism.test.yml
- inventory/host_vars/testbed-node-7.osism.test.yml
- inventory/host_vars/testbed-node-8.osism.test.yml
- inventory/host_vars/testbed-node-9.osism.test.yml
> inventory: add netbox information

- inventory/host_vars/testbed-manager.osism.test.yml
- inventory/host_vars/testbed-node-0.osism.test.yml
- inventory/host_vars/testbed-node-1.osism.test.yml
- inventory/host_vars/testbed-node-2.osism.test.yml
- inventory/host_vars/testbed-node-3.osism.test.yml
- inventory/host_vars/testbed-node-4.osism.test.yml
- inventory/host_vars/testbed-node-5.osism.test.yml
- inventory/host_vars/testbed-node-6.osism.test.yml
- inventory/host_vars/testbed-node-7.osism.test.yml
- inventory/host_vars/testbed-node-8.osism.test.yml
- inventory/host_vars/testbed-node-9.osism.test.yml
> inventory: remove fluentd_host

- environments/custom/playbook-generate-ssh-known-hosts.yml
- environments/generic/configuration.yml
- environments/infrastructure/configuration.yml
- environments/manager/configuration.yml
- environments/monitoring/configuration.yml
- inventory/host_vars/testbed-manager.osism.test.yml
- inventory/host_vars/testbed-node-0.osism.test.yml
- inventory/host_vars/testbed-node-1.osism.test.yml
- inventory/host_vars/testbed-node-2.osism.test.yml
- inventory/host_vars/testbed-node-3.osism.test.yml
- inventory/host_vars/testbed-node-4.osism.test.yml
- inventory/host_vars/testbed-node-5.osism.test.yml
- inventory/host_vars/testbed-node-6.osism.test.yml
- inventory/host_vars/testbed-node-7.osism.test.yml
- inventory/host_vars/testbed-node-8.osism.test.yml
- inventory/host_vars/testbed-node-9.osism.test.yml
> Use internal_interface parameter

- inventory/host_vars/testbed-manager.osism.test.yml
- inventory/host_vars/testbed-node-0.osism.test.yml
- inventory/host_vars/testbed-node-1.osism.test.yml
- inventory/host_vars/testbed-node-2.osism.test.yml
- inventory/host_vars/testbed-node-3.osism.test.yml
- inventory/host_vars/testbed-node-4.osism.test.yml
- inventory/host_vars/testbed-node-5.osism.test.yml
- inventory/host_vars/testbed-node-6.osism.test.yml
- inventory/host_vars/testbed-node-7.osism.test.yml
- inventory/host_vars/testbed-node-8.osism.test.yml
- inventory/host_vars/testbed-node-9.osism.test.yml
> inventory: use the node_id everywhere

- environments/configuration.yml
> Do not cleanup networkd services

- environments/manager/configuration.yml
> manager: deploy celery

- docs/source/usage.rst
> docs: add tailscale

- scripts/006-infrastructure-services-extented.sh
> Enforce the run of patchman-client

- environments/configuration.yml
- environments/manager/configuration.yml
> Move configuration parameters to the manager environment

- terraform/files/manager.sh
> terraform: use ansible-core

- terraform/files/manager.sh
Required by ansible-collection-services
> Install git-lfs

- environments/custom/files/testbed_ceph_devices.fact
- environments/custom/files/testbed_ceph_devices_all.fact
Does not work in the current form on the Pluscloud open.
> Improve the ceph devices fact

- docs/source/usage.rst
- environments/kolla/configuration.yml
It is testbed-manager.testbed.osism.xyz, not just manager...
> Fix the FQDN of the manager node

- contrib/integration-tests/run_test.sh
- docs/source/usage.rst
- terraform/files/manager.sh
partly: osism/issues#65
﻿Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>
> change docker-compose to docker compose v2

- scripts/009-openstack-services-baremetal.sh
> The virtualbmc service requires docker-compose

- environments/manager/configuration.yml
- terraform/files/manager-part-3.yml
> manager: unseal the vault after the first deployment

- terraform/files/manager-part-3.yml
> Initialize the vault

- terraform/files/manager-part-3.yml
> Set INTERACTIVE=false

- environments/configuration.yml
> generic: remove docker_compose_install_type

- terraform/clouds-public.yaml
> add pluscloudopen to clouds-public.yaml

- scripts/001-helper-services.sh
- scripts/002-infrastructure-services-basic.sh
- scripts/003-ceph-services.sh
- scripts/004-openstack-services-basic.sh
- scripts/005-monitoring-services.sh
- scripts/006-infrastructure-services-extended.sh
- scripts/007-openstack-services-extended.sh
- scripts/008-openstack-services-additional.sh
- scripts/009-openstack-services-baremetal.sh
- scripts/999-identity-services.sh
> Migrate to the use of Celery (pt. 1)

- scripts/003-ceph-services.sh
> Fix ceph apply commands

- environments/custom/playbook-generate-ssh-known-hosts.yml
- scripts/001-helper-services.sh
> Use known_hosts role

- environments/manager/configuration.yml
- terraform/files/manager-part-3.yml
> Deploy traefik and enable traefik/netbox integration

- .github/workflows/build-documentation.yml
- .github/workflows/check-ansible-inventory.yml
- .github/workflows/check-ansible-syntax.yml
- .github/workflows/check-python-syntax.yml
- .github/workflows/check-rst-syntax.yml
- .github/workflows/check-terraform-syntax.yml
- .github/workflows/check-yaml-syntax.yml
> github: run branch builds on main only

- environments/infrastructure/configuration.yml
- environments/manager/configuration.yml
- terraform/files/manager-part-3.yml
> Improve the traefik & netbox deployment

- .github/workflows/check-terraform-syntax.yml
- .github/workflows/daily-citycloud.yml
- .github/workflows/daily-pluscloudopen.yml
> github: use terraform 1.1.2

- environments/infrastructure/configuration.yml
> Add nexus configuration

- environments/infrastructure/configuration.yml
> infrastructure: use nexus_traefik

- contrib/terraform/clouds-public.yaml
- contrib/terraform/clouds.yaml.sample
- contrib/terraform/main.tf
- contrib/terraform/secure.yaml.sample
> contrib: add terraform to manage testbed.osism.xyz

- netbox/1000/testbed-manager/a.yaml
- netbox/1000/testbed-node-0/a.yaml
- netbox/1000/testbed-node-1/a.yaml
- netbox/1000/testbed-node-2/a.yaml
- netbox/device-types/Other/manager.yml
- netbox/device-types/Other/node.yml
- netbox/playbook-init.yml
- netbox/playbook-rack-1000.yml
- terraform/files/manager.sh
> Prepare netbox integration

- netbox/playbook-rack-1000.yml
> netbox: add managed-by-osism tag

- terraform/files/manager-part-3.yml
- terraform/files/manager.sh
> terraform: use celery in manager scripts & playbooks

- .ansible-lint
- environments/custom/playbook-fetch-ceph-keys.yml
- scripts/002-infrastructure-services-basic.sh
- scripts/003-ceph-services.sh
- scripts/004-openstack-services-basic.sh
- scripts/008-openstack-services-additional.sh
- scripts/999-identity-services.sh
> Use celery everywhere

- scripts/006-infrastructure-services-extended.sh
> fixed typo in "osism apply"

- environments/manager/configuration.yml
> manager: add osism_api + flower host parameters

- scripts/005-monitoring-services.sh
> It should be 'osism apply netdata'

- environments/manager/configuration.yml
> Fix network_api_url

- netbox/playbook-init.yml
- netbox/playbook-rack-1000.yml
> netbox: use validate_certs: false

- terraform/files/manager.sh
> netbox: connect & disable

- environments/infrastructure/configuration.yml
> netbox: enable bgp & dns plugins

- netbox/1000/testbed-manager/a.yaml
- netbox/1000/testbed-node-0/a.yaml
- netbox/1000/testbed-node-1/a.yaml
- netbox/1000/testbed-node-2/a.yaml
> netbox: add addresses

- netbox/playbook-rack-1000.yml
> netbox: fix roles & set tags

- netbox/1000/testbed-node-3/a.yaml
- netbox/1000/testbed-node-4/a.yaml
- netbox/1000/testbed-node-5/a.yaml
- netbox/1000/testbed-node-6/a.yaml
- netbox/1000/testbed-node-7/a.yaml
- netbox/1000/testbed-node-8/a.yaml
- netbox/playbook-init.yml
- netbox/playbook-rack-1000.yml
> netbox: add more nodes

- netbox/1000/a.yaml
- netbox/1000/testbed-manager/a.yaml
- netbox/1000/testbed-node-0/a.yaml
- netbox/1000/testbed-node-1/a.yaml
- netbox/1000/testbed-node-2/a.yaml
- netbox/1000/testbed-node-3/a.yaml
- netbox/1000/testbed-node-4/a.yaml
- netbox/1000/testbed-node-5/a.yaml
- netbox/1000/testbed-node-6/a.yaml
- netbox/1000/testbed-node-7/a.yaml
- netbox/1000/testbed-node-8/a.yaml
- netbox/playbook-rack-1000.yml
- netbox/templates/Arista.cfg.j2
- terraform/files/manager.sh
> netbox: use an arista switch as sample model

- .github/workflows/check-terraform-syntax.yml
- .github/workflows/daily-citycloud.yml
- .github/workflows/daily-pluscloudopen.yml
- terraform/main.tf
> Use terraform 1.1.4 and require at least terraform 1.1.0

- netbox/templates/Arista.cfg.j2
> netbox: add extra_ parameters to the sample template

- .ansible-lint
- .github/workflows/check-ansible-syntax.yml
- environments/custom/playbook-wireguard.yml
> Use our own ansible-lint-action

- netbox/playbooks/rack-1000.yml
> netbox: add eos tag to testbed-switch-0

- netbox/playbooks/rack-1000.yml
Revert fa1426bc72b59cdda9de34131b0e85230f9fe06a.
> netbox: add custom fields for testbed-switch-0

- netbox/templates/Arista.cfg.j2
> netbox: remove timestampe from the Arista template

- environments/infrastructure/configuration.yml
- scripts/001-helper-services.sh
> Deploy the cgit service

- netbox/1000/testbed-manager/b.yaml
- netbox/1000/testbed-node-0/b.yaml
- netbox/1000/testbed-node-1/b.yaml
- netbox/1000/testbed-node-2/b.yaml
- netbox/1000/testbed-node-3/b.yaml
- netbox/1000/testbed-node-4/b.yaml
- netbox/1000/testbed-node-5/b.yaml
- netbox/1000/testbed-node-6/b.yaml
- netbox/1000/testbed-node-7/b.yaml
- netbox/1000/testbed-node-8/b.yaml
- netbox/1000/testbed-switch-1/a.yaml
- netbox/1000/testbed-switch-2/a.yaml
- netbox/device-types/Other/manager.yml
- netbox/device-types/Other/node.yml
- netbox/inventory/hosts
- netbox/playbooks/rack-1000.yml
> netbox: add more test switches

- environments/infrastructure/configuration.yml
> Use traefik for keycloak

- environments/infrastructure/configuration.yml
* remove parameters that are no longer needed after
switching to Traefik
* move a Nexbox parameter to the correct section
* sort the sections alphabetically
> Cleanup environments/infrastructure/configuration.yml

- environments/manager/configuration.yml
> manager: use traefik for ara-server

- netbox/1000/testbed-switch-1/a.yaml
- netbox/1000/testbed-switch-2/a.yaml
> netbox: connect testbed-switch-[1,2] with testbed-switch-0

- terraform/files/manager.sh
> netbox: set initial state to a

- terraform/files/manager.sh
> netbox: disable all unused interfaces

- inventory/group_vars/testbed-managers.yml
- inventory/group_vars/testbed-nodes.yml
- inventory/host_vars/testbed-manager.testbed.osism.xyz.yml
- inventory/host_vars/testbed-node-0.testbed.osism.xyz.yml
- inventory/host_vars/testbed-node-1.testbed.osism.xyz.yml
- inventory/host_vars/testbed-node-2.testbed.osism.xyz.yml
- inventory/host_vars/testbed-node-3.testbed.osism.xyz.yml
- inventory/host_vars/testbed-node-4.testbed.osism.xyz.yml
- inventory/host_vars/testbed-node-5.testbed.osism.xyz.yml
- inventory/host_vars/testbed-node-6.testbed.osism.xyz.yml
- inventory/host_vars/testbed-node-7.testbed.osism.xyz.yml
- inventory/host_vars/testbed-node-8.testbed.osism.xyz.yml
- inventory/host_vars/testbed-node-9.testbed.osism.xyz.yml
> Use static ansible_host

- terraform/files/manager.sh
> terraform: do not pin ansible-core and use ansible>=5.0.0,<6.0.0

- docs/source/deployment.rst
> Document DNS records and TLS certs #1038

- docs/source/deployment.rst
> Document required virtual resources if not using terraform

- contrib/check_infrastructure_services.sh
> Add two simple tests for Prometheus

- environments/kolla/configuration.yml
> Set debug = True for all OpenStack services

- netbox/playbooks/init.yml
> netbox: wait for the netbox service

- environments/manager/configuration.yml
- environments/manager/secrets.yml
This will fix the listener service
> manager: add missing manager_listener_broker_uri

- environments/custom/playbook-workarounds.yml
- network/vxlan.sh
> Use ansible.utils.ipaddr

- docs/source/notes.rst
- docs/source/usage.rst
> docs: use new osism cli where already possible

- environments/generic/configuration.yml
- environments/infrastructure/configuration.yml
> infrastructure: use traefik for patchman

- docs/source/usage.rst
> docs: fix phpmyadmin url

- environments/kolla/configuration.yml
> kolla: use default rabbitmq_server_additional_erl_args

- docs/source/overview.rst
> insert Xena as default in Overview Documentation

- environments/generic/configuration.yml
> generic: add patchman_server_url

- terraform/environments/gx-scs.tfvars
> - increased memory of node flavor to fix oom errors during deploy-full

- docs/source/deployment.rst
- terraform/environments/betacloud.tfvars
- terraform/variables.tf
> terraform: use SCS flavor names by default

- environments/kolla/files/overlays/cinder/cinder-api.conf
> kolla: remove a cinder workaround that was repaired upstream

- docs/source/usage.rst
> docs: add homer dashboard

- docs/source/deployment.rst
> docs: improve "TLS certificates and hostnames"

- environments/openstack/playbook-bootstrap-basic.yml
- environments/openstack/playbook-bootstrap-keystone.yml
- scripts/004-openstack-services-basic.sh
- scripts/999-identity-services.sh
> Add missing keystone role to the identity testbed

- scripts/999-identity-services.sh
> Deploy Homer in the identity testbed

- environments/configuration.yml
> Do not set cleanup_services_extra

- docs/requirements.txt
- Remove the versions in the requirements.txt to fix upcoming version issues
- This is partly: osism/issues#180
> Deleted the pined versions for the documentation: testbed

- environments/openstack/playbook-bootstrap-refstack.yml
> Set missing file permissions in playbook-bootstrap-refstack.yml

- environments/openstack/playbook-bootstrap-basic.yml
- environments/openstack/playbook-bootstrap-magnum.yml
> Fix some more risky-file-permissions warnings

- docs/source/index.rst
- Add a link to the main documentation.
> Add a link to the main OSISM documentation

- scripts/002-infrastructure-services-basic.sh
> Run a backup of the database to test the backup function

- terraform/scripts/cleanup.py
> terraform: add PREFIX variable to the cleanup script

- docs/source/networking.rst
> docs: Warn about a networking conflict with OVS

- .ansible-lint
- .yamllint.yml
- .zuul.yaml
- docs/source/conf.py
- playbooks/pre-publish.yaml
- playbooks/publish-docs.yaml
- tox.ini
Signed-off-by: Dr. Jens Harbott harbott@osism.tech
> Add docs publishing job

- environments/custom/playbook-keycloak-ldap-federation-config.yml
- environments/custom/playbook-keycloak-oidc-client-config.yml
> Fix yamllint issues

- scripts/002-infrastructure-services-basic.sh
- scripts/006-infrastructure-services-extended.sh
- terraform/files/manager.sh
> terraform: do not deploy extended infra by default

- README.md
- docs/source/usage.rst
- fixed typo
- fixed dead link to homer
- added reference to self-signed OSISM Testbed CA
> fix dead link + mention self-signed OSISM Testbed CA

- scripts/008-openstack-services-additional.sh
> Fix manage-container call in 008-openstack-services-additional.sh

- environments/infrastructure/configuration.yml
- scripts/001-helper-services.sh
> deploy the squid service

- environments/kolla/configuration.yml
> Deploy the enable_elasticsearch_curator

- environments/kolla/configuration.yml
> Set elasticsearch retention time to 1 day

- docs/source/deployment.rst
> docs: add wavestack

- environments/configuration.yml
- terraform/files/manager-part-2.yml
> Use docker 20.10.17

- .ansible-lint
- netbox/playbooks/init.yml
- netbox/playbooks/rack-1000.yml
> Use FQCN in all playbooks for fixing ansible-lint errors

- contrib/ownca/README.md
> contrib/ownca: fix markdown syntax in the README file

- environments/configuration.yml
- environments/manager/configuration.yml
> Move docker_registry parameters

- environments/configuration.yml
- environments/kolla/configuration.yml
> Move kolla vip addresses

- contrib/refstack/prepare.sh
> contrib: use osism apply

- environments/custom/playbook-wipe-partitions.yml
- scripts/003-ceph-services.sh
> On the OTC wipe partitions on all Ceph devices

- .github/workflows/daily-otc.yml
> github: add daily-otc

- contrib/refstack/prepare.sh
- contrib/refstack/tempest.conf
- scripts/100-refstack.sh
- terraform/Makefile
> Fix refstack

- .github/workflows/daily-otc.yml
> For tests deploy yoga @ OTC

- environments/openstack/playbook-bootstrap-basic.yml
> Check if volume type LUKS exists

- environments/kolla/files/overlays/keystone/keystone.conf
- environments/kolla/files/overlays/keystone/wsgi-keystone.conf
Partial osism/issues#130
Signed-off-by: Arvid Requate <requate@univention.de>
> Use mod_oauth2

- README.md
These should help while we migrate from terraform to using only ansible.
> Add some temporary deployment notes

- playbooks/run.yaml
ansible_playbook = path to the ansible-playbook binary
ansible_galaxy = path to the ansible-galaxy binary
> playbooks: make ansible binaries configurable

- playbooks/run.yaml
With the repo_path parameter it is possible to set the location to
the synced repositories
> playbooks: add repo_path parameter

- .zuul.yaml
> zuul: ignore doc/.*

- ansible/manager.sh
- scripts/000-pull-images.sh
Pull later needed images already in the background.
> Improve deployment speed (pt. 2)

- scripts/003-ceph-services.sh
> Improve deployment speed (pt. 3)

- ansible/manager.sh
- doc/source/deployment.rst
- playbooks/run.yaml
- scripts/deploy-services.sh
- terraform/Makefile
- terraform/manager.tf
- terraform/variables.tf
* deployment of the identity testbed or the entire testbed
* move deployment of services to a separate script
> Prepare upgrade tests

- scripts/000-pull-images.sh
> Fix for loop in 000-pull-images.sh

- README.md
> README: remove badges from old github actions

- README.md
Signed-off-by: Felix Kronlage-Dammers <fkr@hazardous.org>
> it is deploy.yaml not run.yaml

- doc/source/usage.rst
> doc: use new scripts to update/upgrade services

- README.md
- doc/source/deployment.rst
> doc: includes content from the README

- doc/source/deployment.rst
> doc: mention the runtime of the "Run part 3" task

- doc/source/overview.rst
> doc: use yoga as new openstack default version & add ceph quincy

- doc/source/requirements.rst
> doc: mention supported ansible/terraform versions

- doc/source/requirements.rst
> doc: add make to the requirements

- .zuul.yaml
> zuul: enable periodic daily testbed-upgrade job

- doc/source/deployment.rst
- playbooks/deploy.yml
> Allow manual deployment of services

- ansible/manager-part-0.yml
- ansible/manager-part-1.yml
- ansible/manager-part-3.yml
- doc/source/deployment.rst
- doc/source/usage.rst
- gilt.yml
- playbooks/deploy.yml
- playbooks/upgrade.yml
- scripts/deploy.sh
- scripts/deploy/000-manager-service.sh
- scripts/set-ceph-version.sh
- scripts/set-manager-version.sh
- scripts/set-openstack-version.sh
- scripts/upgrade.sh
- terraform/Makefile
> Make deploy/upgrade (to) a stable release possible

- terraform/main.tf
> terraform: require at least version 1.2.0

- doc/source/deployment.rst
> doc: improve how to customise a version

- .ansible-lint
Partly osism/issues#323
Signed-off-by: Ramona Beermann <rautenberg@osism.tech>
> Fix Ansible-lint name[template] error

- README.md
> README: change documentation label to installation guide

- doc/source/deployment.rst
- doc/source/preparations.rst
- doc/source/requirements.rst
> doc: document use of basepath & repo_path parameters

- ansible/manager-part-0.yml
- ansible/manager-part-3.yml
- environments/custom/playbook-facts.yml
Partly osism/issues#274
Signed-off-by: Ramona Beermann <rautenberg@osism.tech>
> Add apt lock_timeout attribute to all apt tasks

- doc/source/requirements.rst
- terraform/environments/fuga.tfvars
> Add fuga cloud environment

- .gitignore
- Makefile
- doc/source/index.rst
- doc/source/quickstart.rst
- doc/source/supported-cloud-providers.csv
- playbooks/deploy.yml
- terraform/Makefile
Closes osism/testbed#1362
Closes osism/testbed#1366
Closes osism/testbed#1368
Closes osism/testbed#1369
Closes osism/testbed#1379
> Prepare quick start

- scripts/check.sh
> Add missing ps to osism container command

- scripts/deploy-manager.sh
> Use systemctl to restart the manager service

- environments/kolla/configuration.yml
> kolla: remove defaults that are already in osism/ansible-defaults

- Makefile
- scripts/deploy-identity-services.sh
- scripts/deploy-services.sh
- terraform/Makefile
- terraform/manager.tf
- terraform/variables.tf
> Simplify the deployment of the identity services

- environments/manager/configuration.yml
- environments/manager/images.yml
This reverts commit 8cde024150cecde279648d98d54ea1145ef618ec.
> manager: use netbox v3.4.2

- doc/requirements.txt
- doc/source/conf.py
> docs: use material theme

- Makefile
> If Git repositories are available locally then execute pull

- scripts/deploy/000-manager-service.sh
> Deployment of netbox takes some time

- environments/configuration.yml
- inventory/group_vars/testbed-managers.yml
- inventory/group_vars/testbed-nodes.yml
* use dhcp
* run network role in parallel
> Improve network deployment

- environments/ceph/configuration.yml
- environments/kolla/configuration.yml
- environments/manager/configuration.yml
This way we can speedup the deployment and can reduce the load at quay.io.
> Get most images from harbor.services.osism.tech

- scripts/000-pull-images.sh
> Use new --action argument to pull kolla images

- environments/kolla/configuration.yml
> kolla: fix docker namespace

- environments/kolla/configuration.yml
- scripts/deploy/300-openstack-services-basic.sh
* add missing variable in 4.2.0
* add bootstrap-images playbook
Closes osism/testbed#1461
> Add fixes to be able to use stable releases with main branch

- .ansible-lint
> ansible-lint: only warn about issues

- scripts/deploy/100-ceph-services-basic.sh
> Run ceph validators

- Makefile
- ansible/check-local-versions.yml
Closes osism/testbed#1454
Co-authored-by: Ralf Heiringhoff <ralf.heiringhoff@plusserver.com>
> Check local ansible/terraform versions

- .zuul.yaml
> zuul: deploy openstack zed once a day

- .zuul.yaml
- playbooks/deploy.yml
- scripts/check.sh
- scripts/deploy-manager.sh
- scripts/deploy/000-manager-service.sh
* use central nodesets
* run upgrade tests @ wavestack
> Improve zuul configuration

- .zuul.yaml
- playbooks/deploy.yml
- playbooks/post.yml
- playbooks/pre.yml
- playbooks/upgrade.yml
- playbooks/vars/cloud_envs.yml
> zuul: deploy next & improve nodepool utilisation

- terraform/environments/ovh.tfvars
- terraform/variables.tf
ref: #1468
Signed-off-by: Ralf Heiringhoff <frosty-geek@users.noreply.github.com>
> removed unused tf vars

- playbooks/deploy.yml
- playbooks/post.yml
- playbooks/pre.yml
- playbooks/upgrade.yml
> Make cloud_env fact usable with local testbed deployments

- ansible/manager-part-0.yml
> Use ansible-core in manager-part-0.yml

- .zuul.yaml
- tox.ini
- Delete check via tox
- Enable flake8 check via zuul
- Partly osism/issues#397
Signed-off-by: Ramona Beermann <ramona.beermann@osism.tech>
> Python: Refactor syntax check

- environments/manager/configuration.yml
This reverts commit 9f5a2444c20f92a42e8b5130eac5618ee51ec732.
> Revert "Use mariadb as backend for ara (#1511)"

- playbooks/pre.yml
> zuul: use terraform/scripts/cleanup.py to cleanup resources

- environments/kolla/configuration.yml
Part of osism/cloud-in-a-box#69
> Set neutron availability zone

- environments/kolla/files/overlays/glance.conf
- scripts/upgrade.sh
tempest.api.volume.test_volumes_actions.VolumesActionsTest. \
test_volume_upload
tempest.api.compute.images.test_images_oneserver.ImagesOneSe \
rverTestJSON.test_create_image_specify_multibyte_characte \
r_image_name
tempest.api.compute.images.test_images_oneserver.ImagesOneSe \
rverTestJSON.test_create_delete_image
> Fix failed glance refstack tests

- contrib/rally/tests/task-arguments.yml
- contrib/rally/tests/task.yml
- environments/openstack/configuration.yml
- environments/openstack/playbook-bootstrap-flavors.yml
- environments/openstack/playbook-test.yml
Not for Terraform. This will only be done when the CSPs are converted.
> Use scs flavors v2

- scripts/deploy/310-openstack-services-extended.sh
- scripts/deploy/400-monitoring-services.sh
- scripts/upgrade/310-openstack-services-extended.sh
> Deploy prometheus before ceilometer

- doc/getting_started.md
Signed-off-by: Ramona Beermann <ramona.beermann@osism.tech>
> Documentation: Fix typo in the getting started guideline

- Makefile
- playbooks/deploy.yml
- playbooks/pre.yml
- playbooks/upgrade.yml
- terraform/Makefile
> Use terragrunt

- environments/ceph/configuration.yml
- environments/ceph/secrets.yml
Secrets should only be placed in secrets.yml files.
> ceph: use swift_keystone_password

- doc/preparations.md
Remove outdated GIT clone steps.
> remove outdated git clone steps

- terraform/Makefile
> Supress Terraform warnings if terraformrc file is not present

- .github/renovate.json
> renovate: add terragrunt

- .github/renovate.json
- playbooks/pre.yml
> make renovate functional for terragrunt

- .github/renovate.json
- .github/workflows/check-terraform-syntax.yml
> fix renovate for terraform version

- .github/renovate.json
> Renovate: Trim Terraform version prefix "v".

- environments/kolla/configuration.yml
- environments/kolla/files/overlays/keystone/wsgi-keystone.conf
https://github.com/SovereignCloudStack/issues/issues/313
> Regression: federated OIDC login broken in R4/zed keystone container 

- CONTRIBUTING.md
for now it's a symlink to doc/contribute.md
fixes: https://github.com/osism/testbed/issues/1598
Signed-off-by: Sven Kieske <kieske@osism.tech>
> add a top level contributing.md

- .ansible-lint
- ansible/check-local-versions.yml
- ansible/manager-part-0.yml
- ansible/manager-part-1.yml
- environments/custom/playbook-keycloak-ldap-federation-config.yml
- environments/custom/playbook-keycloak-oidc-client-config.yml
- environments/custom/playbook-openldap-umc-policies.yml
- environments/custom/playbook-umc-admin-ldap.yml
- environments/openstack/playbook-bootstrap-basic.yml
- playbooks/cleanup.yml
- playbooks/deploy-ceph.yml
- playbooks/deploy.yml
- playbooks/pre.yml
- playbooks/upgrade-ceph.yml
- playbooks/upgrade-stable.yml
- playbooks/upgrade.yml
- requirements.yml
- Delete not needed noqas and rules
- Refactor code
- Partly osism/issues#496
Signed-off-by: Ramona Beermann <ramona.beermann@osism.tech>
> Ansible-lint: Refactor rules and noqas

- ansible/check-local-versions.yml
stderr_lines": ["/bin/sh: 1: set: Illegal option -o pipefail"]
> Use bash in "Get terraform version" task

- doc/authentication.md
- doc/configuration.md
- doc/federation.md
- doc/getting_started.md
- doc/important_notes.md
- doc/license.md
- doc/networking.md
- doc/overview.md
- doc/preparations.md
- doc/quickstart.md
- doc/usage.md
* remove useless spaces
* add some missing spaces
* fix Ceph default version
* remove/add services
* remove redundant warning/note
> doc: cleanup (pt. 1)

- environments/kolla/files/overlays/haproxy/services.d/haproxy.cfg
Required because of
https://github.com/osism/container-image-kolla-ansible/commit/de6f99670ee951eb1f5d40d727d49708e05f6304
> kolla: use ansible_facts instead of ansible_hostname

- doc/federation.md
- doc/important_notes.md
- doc/preparations.md
- doc/requirements.md
- doc/usage.md
Do not use blockquotes inside warning/note blocks.
> doc: cleanup (pt. 2)

- .github/renovate.json
- .zuul.yaml
Also add .github/ directory to irrelevant files in zuul.yaml
> renovate: update terraform version in pre play

- doc/requirements.md
The cloud provider information list in the requirements.md file has been transferred into a table.
> doc: update cloud provider information table

- environments/custom/configuration.yml
- environments/custom/playbook-keycloak-oidc-client-config.yml
- environments/kolla/files/overlays/horizon/custom_local_settings
- environments/kolla/files/overlays/keystone/wsgi-keystone.conf
For more info: 
* https://github.com/SovereignCloudStack/issues/issues/347
* https://input.scs.community/2023-scs-horizon-webslo-solution3?view
> Fix Single Logout on federated scenarios.

- environments/kolla/configuration.yml
- environments/kolla/files/overlays/horizon/custom_local_settings
- environments/kolla/files/overlays/keystone/wsgi-keystone.conf
Fix possible redirect loop on certain browsers.
> Horizon logout doesn't logout federated OIDC user 

- .zuul.yaml
Clean up a few more little things and add an abstract testbed-deploy job definition.
> zuul: run refstack on testbed-deploy job

- .ansible-lint
- environments/kolla/configuration.yml
- environments/kolla/files/overlays/ceilometer/event_pipeline.yaml
- environments/kolla/files/overlays/ceilometer/pipeline.yaml
this adds pushing events directly to the metering api
> metering: Feature/add metering sink

- scripts/upgrade/310-openstack-services-extended.sh
> Add missing space in 310-openstack-services-extended.sh

- environments/configuration.yml
> Explain osism_serial_default parameter and use defaults for osism_serial

- Makefile
> Fix prepare target in Makefile

- scripts/deploy/000-manager-service.sh
fixes setups where prefix is set
> add openstack-control-plane label to all hosts labeled control-plane

- releasenotes/notes/use-integrated-ironic-agent-download-tasks-f50cd718af79db25.yaml
- scripts/deploy/320-openstack-services-baremetal.sh
- scripts/upgrade/320-openstack-services-baremetal.sh
> Use playbook tasks to download required ironic images

- .zuul.yaml
- playbooks/managerless/deploy.yml
- playbooks/managerless/files/managerless-part-5.yml
- playbooks/managerless/pre.yml
- playbooks/managerless/templates/sshuttle.service.j2
- playbooks/managerless/templates/sshuttle.sh.j2
Also disable post testbed-deploy-stable job.
> managerless: restructuring (pt. 1)

- scripts/000-pull-images.sh
This will avoid timeout issues in subsequent steps.
> Wait for pull of images

- scripts/000-pull-images.sh
Related to 18e1fb66a38f6d6e68c9d59c90e5994caa0c2a00
> Fix debug output

- environments/infrastructure/configuration.yml
> infrastructure: set phpmyadmin_database_host

- environments/kolla/files/overlays/keystone/policy.yaml
This will fix the following tempest test:
tempest.api.identity.v3.test_domains.DefaultDomainTestJSON.test_default_domain_exists
> Sync keystone police with current SCS state

- environments/configuration.yml
- releasenotes/notes/network-serial-18fe3b6ae7791936.yaml
Change the default of serial for the network play to configure all nodes in parallel.
> Set osism_serial["network"] = 100%

- scripts/deploy-manager.sh
It's already part of the bootstrap play.
> Do not run hosts play twice

- ansible/manager-part-0.yml
fixes: https://github.com/osism/testbed/issues/1834
> check for supported ubuntu version

- terraform/environments/ci.tfvars
- terraform/environments/regiocloud.tfvars
> Use SCS-4V-16 flavors in the CI & REGIO.cloud profile

- environments/custom/files/testbed_ceph_devices.fact
- environments/custom/files/testbed_ceph_devices_all.fact
> Do not use swap devices for ceph

- ansible/check-local-versions.yml
> Check python version

- environments/kolla/configuration.yml
Is now part of the defaults & overlays.
> kolla: remove ceph_nova_keyring parameter

- Makefile
see https://github.com/osism/osism.github.io/pull/305
> align to https://github.com/osism/osism.github.io/pull/305

- environments/openstack/playbook-test.yml
> openstack: in the test play do not build port in advance

- environments/kolla/files/overlays/keystone/policy.yaml
> Sync domain-manager policy

- scripts/set-manager-version.sh
This way it's the same like in the upgrade.sh script.
> Fix gilt installation/usage in set-manager-version.sh

- inventory/20-roles
Related to 78cc03e342e94260a7083a3dc7043ce814cdbe7d
> The k3s master nodes are already nodes

- scripts/deploy-services.sh
- scripts/deploy/200-infrastructure-services-basic.sh
7.0.0a contains various errors.
> Deploy kubernetes/keycloak only as of 7.0.0b

- scripts/deploy/100-ceph-services-basic.sh
Related to c1acecea1ce5e6703f997137703add1abb5f5baf
> ceph: run reconciler

- README.md
- ansible/check-local-versions.yml
- terraform/Makefile
The testbed guide has been moved in [1].
[1]
https://github.com/osism/osism.github.io/pull/340
> Update references to the testbed guide

- environments/rook/configuration.yml
- environments/rook/images.yml
- environments/rook/secrets.yml
Required in preparation of the deployment of the rook operator.
> Add an empty rook environment

- ansible/manager-part-3.yml
- playbooks/managerless/deploy.yml
> Fix managerless deployment

- playbooks/managerless/files/managerless-part-3.yml
Related to c3f89c7e0ca0ec38ee075f97f3d998b8702f33d2
> Fix managerless deployment (pt. 2)

- README.md
- ansible/check-local-versions.yml
- ansible/manager-part-0.yml
- terraform/Makefile
Part of https://github.com/osism/issues/issues/927
> Replace osism.github.io with osism.tech

- ansible/check-local-versions.yml
replace head cmd in pipeline with sed, because head fails sometimes with exit code 141. Fix tofu version check.
> replace head in pipeline with sed

- scripts/bootstrap/300-openstack-services.sh
Related to 4ec646e017246e03dd2fb5b2d10f005e065de2ad
> Also add recommended flavors

- environments/openstack/playbook-bootstrap-flavors.yml
- scripts/bootstrap/300-openstack-services.sh
Related to 4ec646e017246e03dd2fb5b2d10f005e065de2ad
> Add missing flavor extra specs

- scripts/deploy-manager.sh
Use force when creating symbolic links to make link creation idempotent. During the lifecycle of a testbed the script creating the links may be called multiple times.
> Force creation of symbolic links

- gilt.yml
> Use set-versions.py in gilt configuration

- environments/openstack/playbook-bootstrap-basic.yml
- environments/openstack/playbook-test.yml
Invalid input for operation: Requested MTU is too big, maximum is 1342.
Related to 56cce0107fd0454362c629faf3691680d9870262.
> Fix MTU size

- ansible/manager-part-2.yml
Related to fc12e5643a37413f2ab0201cab9401a86a0a219b
> Also pin docker version for OSISM latest

- Makefile
https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html
> Use .PHONY in the Makefile

- terraform/Makefile
https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html
> testbed: use .PHONY in the Makefile

- .github/renovate.json
Related to 3e35d5c17bff07a197cffb8f34218b67b0f96539
> renovate: add opentofu_version to the configuration itself

- Makefile
Problems on Ubuntu 24.04, so moving to the simpler invocation.
> replace virtualenv

- playbooks/managerless/pre.yml
- playbooks/pre.yml
Still related to this issue:
fatal: [testbed-manager.testbed.osism.xyz]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: Not supported URL scheme http+docker"}
> zuul: fix python requirements

- scripts/deploy/300-openstack-services-basic.sh
- scripts/upgrade/300-openstack-services-basic.sh
Related to 67cd6791c4122075bc94506df9adacf482c85717
> Remove some more files to disable Keystone/Keycloak integration

- scripts/deploy/000-manager-service.sh
- scripts/upgrade.sh
Related to osism/terraform-base#60
> Make it possible to disable ARA via terraform variable ara

- playbooks/managerless/pre.yml
Related to f6298bedf88cc78ee18b5e5cbdf8ea8e7819533e
> managerless: add missing become

- ansible/manager-part-0.yml
This way we ensure to overwrite maybe already existing Ansible collections.
> Force the installation of local Ansible collections

- Makefile
- environments/rook/configuration.yml
- playbooks/deploy.yml
- scripts/check-ceph-services.sh
- scripts/check-services.sh
- scripts/check/100-rook-services.sh
- scripts/deploy-ceph-services.sh
- scripts/deploy-manager.sh
- scripts/deploy-services.sh
- scripts/deploy/100-rook-services.sh
- scripts/upgrade-ceph-services.sh
- scripts/upgrade-services.sh
- scripts/upgrade/100-rook-services.sh
- terraform/Makefile
This is part of https://github.com/osism/issues/issues/884
> Enable Rook deployments (#884)

- environments/custom/files/testbed_ceph_devices.fact
- environments/custom/files/testbed_ceph_devices_all.fact
- environments/custom/files/testbed_ceph_osd_devices.fact
- environments/custom/files/testbed_ceph_osd_devices_all.fact
Required to make the facts also usable on Ubuntu 24.04.
> custom: fix devices facts

- scripts/prepare-ceph-configuration.sh
Related to c1d508a6fd178e96abd43d433c2f146177bde5dc
> custom: always make the Ceph LMV2 plays available

- scripts/prepare-ceph-configuration.sh
Related to c1d508a6fd178e96abd43d433c2f146177bde5dc
> Add missing template for the Ceph LVM2 play

- scripts/prepare-ceph-configuration.sh
Related to c1d508a6fd178e96abd43d433c2f146177bde5dc
> custom: add ceph-pools play

- terraform/environments/ci.tfvars
Related to 10e4ef638d7a3854a74f4f2699d9409db5452ab9
> terraform: remove is_zuul from ci vars

- .flake8
- environments/kolla/files/overlays/horizon/_9999-custom-settings.py
Required by OpenStack Kolla >= 2024.1
Related to osism/issues#1073
> Add _9999-custom-settings.py file

- environments/infrastructure/configuration.yml
- inventory/group_vars/testbed-managers.yml
- inventory/group_vars/testbed-nodes.yml
Depends on https://github.com/techno-tim/k3s-ansible/pull/554
> k3s: use cilium

- environments/infrastructure/configuration.yml
- inventory/group_vars/testbed-managers.yml
- inventory/group_vars/testbed-nodes.yml
Revert 65b99b2b877edc1e48674e9f32d7879a8244f23d
> k3s: back to flannel for the moment

- Makefile
- terraform/Makefile
This will set image_user and image_nod_user vars to ensure that the username is also known inside the instances.
> terraform: add IMAGE_USERNAME to auto.tfvars file

- terraform/environments/ci-centos-stream-9.tfvars
- terraform/environments/ci-debian-12.tfvars
- terraform/environments/ci-ubuntu-22.04.tfvars
- terraform/environments/ci-ubuntu-24.04.tfvars
* CentOS Stream 9
* Debian 12
* Ubuntu 22.04
* Ubuntu 24.04
> terraform: add additional CI environment files

- environments/custom/playbook-facts.yml
The OS family is Debian and not Ubuntu.
> custom: fix wrong ansible_os_family

- scripts/prepare-ceph-configuration.sh
Related to ecf91126e828a0e6fc3dbd6863d625b3da737fc9
> Make sure that ceph_docker_registry is removed on CentOS

- Makefile
Related to 29e3739df0ac20245cf30f04f079a0ec5e125d7b
> Use testbed_cloud instead of cloud_env in Makefile

- scripts/deploy-in-a-nutshell.sh
- scripts/deploy-services.sh
- scripts/upgrade-services.sh
This reverts commit f0aa1f9c78eebdd725c62f6a28fb75f253674115.
> Pull images & do not use local registry for nutshell deploy

- scripts/deploy-in-a-nutshell.sh
- scripts/set-docker-registry.sh
Related to 049ed0ac004b1c2d5e2e8df900d135d5bffa8932
> Use osism.harbor.regio.digital for nutshell deployment

- .zuul.yaml
- playbooks/deploy.yml
> zuul: do not hardcode ci- prefix for terraform environments

- playbooks/deploy.yml
- playbooks/vars/mappings.yml
Related to 0fc4c324089144c61248acabc3580fb8966bb454
> Set default image username & fix CI image usernames

- scripts/bootstrap/300-openstack-services.sh
- scripts/check.sh
- scripts/check/100-ceph-services.sh
- scripts/deploy/100-ceph-services.sh
- scripts/deploy/200-infrastructure-services.sh
- scripts/prepare-wireguard-configuration.sh
Related to c8f62f28a3cd78cb514148da82fead016a142f1d.
> Ensure that MANAGER_VERSION != latest

- ansible/manager-part-1.yml
Related to 5512529b3a95a29cf8afb3ac7e6ca72d91ac7ca4
> ansible: use jinja2

- scripts/enable-resource-nodes.sh
Related to 3a94d651776fb6ba7b85767b489116265101bbd3
> Also enable testbed-node-3

- environments/rook/configuration.yml
Related to 53285233c62e024fd0f90ab8a3cd0f237e797269
> rook: fix storage nodes

- scripts/deploy/100-rook-services.sh
> rook: enable ceph orch backend via CLI

- inventory/10-custom
- scripts/enable-resource-nodes.sh
Related to 3a94d651776fb6ba7b85767b489116265101bbd3
> Use testbed-node-[0-2] on small testbed as resource nodes

- scripts/deploy/000-manager-service.sh
Related to e3380d01f3789db3494dbd88d5b85b7f6ce2fc62
> Initialize netbox again with latest

- scripts/deploy/100-rook-services.sh
Related to 8076e73e7e5000667fc569f4f6ec4b7bacd501dc
> Fix wrong rook loadbalancer rgw port

- ansible/manager-part-1.yml
- playbooks/deploy.yml
- terraform/Makefile
Related to 6e4837f8bb4da406f9535681f6282f48ba79d91a
> Remove old is_zuul variables/parameters

- ansible/manager-part-3.yml
Related to 6e4837f8bb4da406f9535681f6282f48ba79d91a
> Fix check for IS_ZUUL in /opt/manager-vars.sh

- environments/custom/playbook-pull-images.yml
This preheats the Nexus cache.
> Pull images in background & only on the first control node

- terraform/environments/artcodix.tfvars
Let's have a profile for artcodix as well.
> Environment for Artcodix (aka cnds).

- ansible/manager-part-3.yml
- environments/configuration.yml
- inventory/group_vars/all/registries.yml
- scripts/disable-local-registry.sh
- scripts/prepare-ceph-configuration.sh
- scripts/set-docker-registry.sh
Makes it easier to customize these parameters for specific hosts.
> Move registry parameters to the inventory

- environments/kolla/configuration.yml
Related to e5ab2510cd3dc2a1c8915dfa55050a7eafd234c4
> Disable RabbitMQ HA queues

- scripts/deploy/000-manager-service.sh
Revert 3fc9efdbac4718d09508df86c890b26735d78c5f
> Remove squid workaround

- environments/rook/configuration.yml
- environments/rook/secrets.yml
- scripts/deploy/100-rook-services.sh
Initial adaption of the Keystone/Swift integration in Rook.
Fixes [osism/issues/issues/1027](https://github.com/osism/issues/issues/1027)
> rook: Values regarding Keystone/Swift

- environments/generic/configuration.yml
The parameter are part of the osism/defaults repository.
> Remove dotfiles parameters

- scripts/prepare-wireguard-configuration.sh
Required because of
https://github.com/osism/ansible-collection-services/commit/1d705ecf38fbab424667feb934597a0f8bc5741c
> Fix prepare-wireguard-configuration.sh script

- environments/openstack/playbook-bootstrap-images.yml
This is only kept as an example. However, it should still be up to date.
> Updates images in bootstrap-images play

- playbooks/deploy.yml
Related to 51de4735a832336c1ecebfe1d399fca51ae8a57d
> Use /bin/bash

- ansible/manager-part-1.yml
Related to fe2348549232ad42593d39933615f3c3c7f3fea5
> Remove wrong quotes

- ansible/manager-part-2.yml
Related to 052e65d133004d0ef9320fb60b1dcef0e2b05be3
> Fix typo in debug task

- scripts/bootstrap-services.sh
Related to eb878af625f26f2f4e9d5055861d0a6530b37c89
> Fix "300-openstack-services.sh: not found" issue

- playbooks/deploy.yml
Related to eb878af625f26f2f4e9d5055861d0a6530b37c89
> Fix "302-openstack-tempest.sh: No such file or directory" issue

- inventory/group_vars/testbed-control-nodes.yml
- inventory/group_vars/testbed-nodes.yml
- scripts/deploy/000-manager.sh
Related to 162eec6e76f3a7aa3cd3873b679bb5f1f1a46465
> Add VXLAN interfaces to all nodes

- environments/custom/playbook-baremetal-prepare.yml
- inventory/group_vars/all/vxlan.yml
Related to 162eec6e76f3a7aa3cd3873b679bb5f1f1a46465
> Add manager to the dests of the netdev VXLAN interfaces

- scripts/deploy/300-openstack.sh
- scripts/upgrade/300-openstack.sh
There is now a dedicated baremetal testbed.
> Do not deploy/upgrade ironic by default

- scripts/check/200-infrastructure.sh
Related to 0e3e7135a2d131117726c66d5e0d9561db7481b7
> Use root_shard in the 200-infrastructure.sh check script

- scripts/deploy/310-openstack-services-extended.sh
- scripts/pull-images.sh
- scripts/upgrade/310-openstack-services-extended.sh
We don't usually use heat anywhere. We don't test it. Let's stop deloying it in the testbed.
> Do not deploy heat

- scripts/deploy/000-manager.sh
> Only use netbox for OSISM >= 9.0.0 and latest

- scripts/bootstrap/000-netbox.sh
> Use new osism netbox manage in 000-netbox.sh script

- scripts/bootstrap/000-netbox.sh
Related to 7abef6a237b0e4af67da7115ffe3eaeaaa147408
> Run netbox plays in parallel

- environments/custom/playbook-baremetal-netbox.yml
- environments/custom/templates/baremetal-netbox-device.yml.j2
- netbox/devicetypes/Other/baremetal-device.yml
- netbox/devicetypes/Other/baremetal-housing.yml
- netbox/devicetypes/Other/node.yml
- netbox/resources/100-initialise.yml
- netbox/resources/200-rack-1000.yml
- netbox/resources/300-testbed-manager.yml
- netbox/resources/300-testbed-node-0.yml
- netbox/resources/300-testbed-node-1.yml
- netbox/resources/300-testbed-node-2.yml
- netbox/resources/300-testbed-node-3.yml
- netbox/resources/300-testbed-node-4.yml
- netbox/resources/300-testbed-node-5.yml
- netbox/resources/300-testbed-node-6.yml
- netbox/resources/300-testbed-node-7.yml
- netbox/resources/300-testbed-node-8.yml
- netbox/resources/300-testbed-node-9.yml
- scripts/deploy-baremetal.sh
During baremetal scenarios, update netbox with resources created by tenks.
> Update netbox with tenks resources

- environments/custom/templates/baremetal-netbox-device.yml.j2
- environments/manager/files/conductor.yml
- netbox/resources/200-rack-1000.yml
Part of https://github.com/osism/issues/issues/1228
> Add conductor.yml and oob custom fields for tenks nodes

- netbox/resources/300-testbed-manager.yml
- netbox/resources/300-testbed-node-0.yml
- netbox/resources/300-testbed-node-1.yml
- netbox/resources/300-testbed-node-3.yml
- netbox/resources/300-testbed-node-4.yml
- netbox/resources/300-testbed-node-5.yml
- netbox/resources/300-testbed-node-6.yml
- netbox/resources/300-testbed-node-7.yml
- netbox/resources/300-testbed-node-8.yml
- netbox/resources/300-testbed-node-9.yml
- netbox/resources/300-testbed-switch-0.yml
- netbox/resources/300-testbed-switch-1.yml
- netbox/resources/300-testbed-switch-2.yml
Related to 0336186c74b76aa5689aae7dedbdae8b7e7756ef
> netbox: fix configuration

- netbox/resources/100-initialise.yml
- netbox/resources/200-rack-1000.yml
- netbox/resources/300-testbed-manager.yml
- netbox/resources/300-testbed-node-0.yml
- netbox/resources/300-testbed-node-1.yml
- netbox/resources/300-testbed-node-2.yml
- netbox/resources/300-testbed-node-3.yml
- netbox/resources/300-testbed-node-4.yml
- netbox/resources/300-testbed-node-5.yml
- netbox/resources/300-testbed-node-6.yml
- netbox/resources/300-testbed-node-7.yml
- netbox/resources/300-testbed-node-8.yml
- netbox/resources/300-testbed-node-9.yml
- netbox/resources/300-testbed-switch-0.yml
- netbox/resources/300-testbed-switch-1.yml
- netbox/resources/300-testbed-switch-2.yml
- netbox/resources/300-testbed-switch-3.yml
- netbox/resources/300-testbed-switch-oob.yml
Related to 0a5ec277aeb4d3efc7e329dd9561f81343d620c8
> Fix netbox configuration

- ansible/manager-part-3.yml
- inventory/20-roles
- scripts/deploy-baremetal.sh
- scripts/deploy/000-manager.sh
- scripts/upgrade.sh
Related to 94d371d20ac789cea6d39f01979b8c56bd2f4276
> Remove netbox from manager deployment script

- ansible/manager-part-1.yml
- ansible/manager-part-2.yml
Related to ac6029c8afe6a6301cdc5a01e3a11ec088baf2d0
> Use venv for gilt
